### ISSUE TITLE
Migrate functional spec into Wiki - part 1

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1001]
1. Prototype with dependencies are great. Next step is to gradually move the functional specs out of Pages and Word document so we no longer have to deal with those. 

2. Need documentation of "How to edit functional spec" so we don't break it. 

[List of components to migrate to Wiki TBD]

## Discussion notes

Roughly speaking 15 components / wk. 

1. prioritizing content item/group/block/section (4)
2. start with UI component this sprint (aim to do another 10)

**Comment by RobertaJHahn** [comment]
Will be added to the June 1 Design planning meeting.
