### ISSUE TITLE
[Website] Designing page - redesign (content and structure)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#1003]
## Objective:

We need to take another look at the Designing page to make sure all the content updates to date.

## Note:

Some adopters finding insight might come in by the end of Q2. We can work on the Designing page based on the findings.

### 👉 Task detail and additional resources will be provided by the end of Q2.

**Comment by RobertaJHahn** [comment]
Dup of (#6445 )  Closing
