### ISSUE TITLE
Website: [Masthead] Document reason why Masthead must stay white

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1015]
### Document the reasons why IBM.com corporate masthead is locked to White theme

Current page: https://www.ibm.com/standards/carbon/components/masthead

**Dark theme doesn't add value for exploration experiences (marketing, learn).**

1. Position of masthead are out of the way, allowing the rest of the page designs to take on any theme. Dark lead space and themed pages do not need a dark masthead to work well visually.
2. Dark lead spaces often benefits from white masthead looking separate and out of the way, because masthead contains global navigations, and not as relevant. 
3. A consistent theme helps with brand recognition 

**Dark and light mode switching is discouraged for Dotcom, and this logic extends to masthead.**

3. A big portion of the pages featuring Dotcom Masthead are marketing pages. These pages are reading oriented, heavy in imagery and logo. Theme switching could cause unexpected results at scale. 
4. Even in Cloud console, mode switching doesn't affect navigation bar, which stays dark 
5. Allowing theme mode switching is a statement that the space is a productive one, where users are expected return often to get the job done. In marketing pages, users or visitors are not expected to return as frequently, and the stability of the appearance of page is more important for instant recognition.

**Comment by JennySanchez** [comment]
@shixiedesign Are you imaging the content will live in the Wiki or on the website?

**Comment by JBrandwine** [comment]
[https://app.zenhub.com/files/202376156/e6cd031d-a149-4d82-a0a7-6fdbe8b78fbb/download](https://app.zenhub.com/files/202376156/e6cd031d-a149-4d82-a0a7-6fdbe8b78fbb/download)

**Comment by JBrandwine** [comment]
@shixiedesign ready for review, thanks!

**Comment by JBrandwine** [comment]
Updated. copy:

**Color Theme**

As a fundamental component of the IBM.com web experience, the white masthead should remain consistent, creating a branded anchor across all pages that stands out from the dark lead space. In addition to providing brand recognition, a consistent masthead removes variability when building graphic heavy marketing pages, which can cause unexpected results at scale.

For individual use cases, if a color theme change will have a positive impact on the web experience, please contact us.
