### ISSUE TITLE
[Footer] Update images on website component page 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1018]
1. Footer V2's design is slightly changed. We should update the website so images there are the correct ones reflecting what code would deliver. 
2. No need for larger content restructure yet. Keep the changes scoped to "remove wrong info" only
3. This PR should not be merged until new design is implemented & released.

**Comment by DragosRistici** [comment]
The draft PR for images: [1071](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1071)
The draft PR for page updates: [1070](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1070)
To be merged at a later date, after the dev updates.
