### ISSUE TITLE
 Add "IBM Workplace Design" to nav switcher

### ISSUE THREAD

**Issue by KSandeep5** [carbon-design-system/carbon-for-ibm-dotcom-website#1027]
**Describe the solution you'd like** 
Adding IBM Workplace design to the Nav Switcher, as it currently is with IBM Design Language and IBM Brand Center.

Url to be added:
https://www.ibm.com/design/workplace/

"IBM Workplace Design" site to be added within "implementation" under " IBM Event Design".

**Comment by JennySanchez** [comment]
@KSandeep5 Thank you for submitting the issue. The switcher is updated on the [Carbon for IBM.com webiste](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/), and now you should see the "IBM Workplace Design" on the list (see screenshot below for reference).

![Screen Shot 2021-06-16 at 11.40.59 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/df6a6099-5ed6-4d64-9906-7271c226cd00)

**Comment by JennySanchez** [comment]
@kennylam Thank you for taking a look!
