### ISSUE TITLE
Audit Carbon for IBM.com website content 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1041]
Going through the existing site for a holistic understanding of our content. 

- [List of resources](https://ibm.ent.box.com/notes/824637485498) to review 

- [Airtable] with classifications, content audit, and notes of content items to fix. (https://airtable.com/tblIhPhmgN6aJRQYO/viwFdx8cnecEw6AUp?blocks=hide) 

Some materials for reference: 
- [A sitemap draft for consideration](https://www.figma.com/file/Nkn8gqjyKVEbIiWcBRUsMm/Sitemap?node-id=0%3A1) 
- Google analytics report shows top traffic pages 
[https://app.zenhub.com/files/202376156/1df26d56-dfe2-4447-b58c-2c8649ee394e/download](https://app.zenhub.com/files/202376156/1df26d56-dfe2-4447-b58c-2c8649ee394e/download)

**Comment by janchild** [comment]
[Content audit ](https://airtable.com/tblIhPhmgN6aJRQYO/viwFdx8cnecEw6AUp?blocks=hide)Airtable resource created and will now be used for work moving forward.
