### ISSUE TITLE
[Website] Website inventory page creation

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#1045]
### User needs:

As a Carbon for IBM.com owner, I need to see how many website pages, categories, and website pages are published on the website. I also need a way to know when the page is published and edited to better view the website's growth.

### Steps: 

- [x] Ideate how we can have the inventory list live on the website or website repo wiki. 
- [x] Ideate the possibility of better inventory list management or data automation.
- [x] Explore the ideas with the prototype or PR
- [x] Share the prototype with Linda
- [ ] Make update if needed

### Acceptance criteria

- [ ] An up-to-date Carbon for IBM.com website inventory list is available for viewing.

**Comment by JennySanchez** [comment]
@photodow The page looks great and meets my need. Thank you so much. Our next step will be sharing the page with @ljcarot before merging it if she has questions or feedback.

**Comment by ljcarot** [comment]
Is there a link to where I can see the inventory?  @photodow @JennySanchez

**Comment by photodow** [comment]
Is this what you're looking for @ljcarot? https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1043/page-inventory/

**Comment by ljcarot** [comment]
Thanks! @photodow

**Comment by JennySanchez** [comment]
@ljcarot @photodow Thank you both for the review again. This page will be merged soon. [Task issue #1059](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/1059) created for me to add all the dates in and get the data linked.
