### ISSUE TITLE
Website: Component guidance template

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1077]
### Task
Need a new **Component page** template so usage guidance and specs are surfaced to adopters better, and information better connected. 

### Problem 

Currently most component page guidance is created using below template:

```
- Default
- (Variations) 
- Behaviors
- Design and functional specifications
- Development documentation
- Feedback

```

A few complains about the current template include 
- Design & functional specs are too buried, reducing discoverability and making it hard for returning users to access. 
- "Default" etc are not informative section names
- Need to allow more flexibility depending on the component's complexity and needs

### Ideas

From the top of my head, some potential candidates for what goes into the template. 

**Always show:** 

- Design intent (usage)
- Function & behaviors
- Content guidance (required vs optional content, recommended char count and cardinality) 

**Potentially good to show:** 

- Explain build in logic
- Anatomy
- Use case examples
- Live demo? 
- Do’s and Don’ts
- Accessibility

**Comment by janchild** [comment]
Work in progress here: https://www.notion.so/carbondesignsystem/Component-overhaul-a21c7132a804402684f9e3f4e7f44d56

**Comment by janchild** [comment]
@shixiedesign Work is in progress. Will need to continue in next sprint.

**Comment by janchild** [comment]
"Kitchen sink" template draft for team discussion: https://www.notion.so/carbondesignsystem/Component-guidance-5e065eaaf21e47549717025c2a07f80f

**Comment by janchild** [comment]
Here are the latest templates in progress. I've laid the templates out in Sketch so it's easier to see how the finals will look. I worked through this content in detail with @RichKummer for his current PR and this is where it landed. 

1. Single component template, showing the maximum number of headings that _could_ be used. 

2. Multicomponent template, using the same structure as the single component but with component nesting and with each component name appearing in the anchorlinks for easy access. In this template, I've also explored what each component would look like with less content the further you move down the page. (This is the case for alot of our components currently.)

[Single component template.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/files/6962335/Single.component.template.pdf)

[Multicomponent template.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/files/6962337/Multicomponent.template.pdf)

**Comment by janchild** [comment]
Thanks everyone for the review in Huddle this week. I'm attaching the updated versions here. Will also attach to the [new ticket](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/1133). 

[Single component template v2.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/files/6984415/Single.component.template.v2.pdf)

[Multicomponent template v2.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/files/6984416/Multicomponent.template.v2.pdf)
