### ISSUE TITLE
Website: add logo placement grid to Logo grid page

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1079]
The guide for logo placement: 
[Logo placement spec](https://app.zenhub.com/files/202376156/0f114a98-0d4f-409f-b3a3-3068e11d24df/download) 
Box for above file: https://ibm.box.com/s/2c2dt2fivbmbcce29oul7hjaktjaqj26

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/58de17f9-3473-4052-8860-a402037c5cb5)

**Comment by shixiedesign** [comment]
https://ibm.box.com/s/2c2dt2fivbmbcce29oul7hjaktjaqj26
[Logo placement spec](https://app.zenhub.com/files/202376156/0f114a98-0d4f-409f-b3a3-3068e11d24df/download)a

**Comment by oliviaflory** [comment]
Notes

When possible, use horizontally oriented logos to avoid vertical spacing issues
Safe space on grid
Use ratios in the grid
Optically align.

**Comment by oliviaflory** [comment]
@shixiedesign if you have a moment would love your thoughts on the logo grid guidelines. As discussed, I just added the centered 4:3 placement to logo grid, and we will work on incorporating left aligned logos and sizes when we do Logo card explorations.

![logo-grid-website-mock](https://user-images.githubusercontent.com/45692622/125372545-58680400-e351-11eb-9b9a-49ade9af24ee.jpg)

**Comment by oliviaflory** [comment]
Documenting feedback from slack:

Outline changes:
- Logo placement
   - Grid template
   - Alignment
- Tips and techniques
   - Orientation
   - Type
   - Color

- [ ] update outline 

Under `Logo placement > Alignment` I think a more common mistake is people use the largest width and ignore height of grid
- [ ] update visual example to full width

**Comment by oliviaflory** [comment]
Logos on IBM.com
- https://www.ibm.com/watson
- https://www.ibm.com/cloud
