### ISSUE TITLE
Website [Card - pictogram]: update Card page to reflect new design

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1107]
### Task

1. Add a new page to Carbon for IBM.com documenting the general usage guidance of `Card - pictogram`. 
2. Design and add a thumbnail of the component to Component overview page

### Useful resources

- Design page mockup using [Gatsby theme resources](https://carbondesignsystem.com/designing/design-resources/#gatsby-theme-resources)
- Create images **strictly** using Image production guidelines. Find sketchfiles from same link above 
- Create thumbnail image on the Components overview page - use the master Sketch work file [here](https://ibm.box.com/s/hyzeqfb7zqov1j3es4p6kplr6r15flat) to get started.
- For general contribution - Please visit the [Contributing page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/overview) for information and process detail.
- For how to create and submit PR - Please visit the [Submitting a Pull Request section](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/docs/developing.md#submitting-a-pull-request) to learn more.
- For Markdown best practices - Please visit the [Production guideline](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Carbon-for-IBM.com-Production-guidelines) to learn more.

**Comment by RobertaJHahn** [comment]
This page will be merged into the "card" page and is no longer needed.  Closing.
