### ISSUE TITLE
Website [Contribution] Update with component template

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1133]
This ticket is for the work updating the Contributing > Components page of the website.

- [x] The new component templates have been included in Markdown
- [x] Link to a Sketch file with templates is available to download from Box.
- [x] The page content had a general tidy up and reordering.

Associated PR: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1392

**Comment by janchild** [comment]
Here are the latest component templates, with feedback included from our August 12 Huddle. 

[Single component template v2.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/files/6984424/Single.component.template.v2.pdf)

[Multicomponent template v2.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/files/6984425/Multicomponent.template.v2.pdf)

**Comment by janchild** [comment]
Increasing estimate because I'm spending time refining, reviewing PRs, and reviewing content guidance tables.
