### ISSUE TITLE
Website [About Carbon for IBM.com] Migrating to C4IBM content

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1137]
### Task

The current pages under this section are: 
https://www.ibm.com/standards/carbon/about-carbon-for-ibm.com/what-is-carbon-for-ibm.com/
https://www.ibm.com/standards/carbon/about-carbon-for-ibm.com/get-started

The content is not succinct and need much shorter page titles to fit within the design. Ideally a quick content pass to trim down unnecessary content. Proposed draft page titles: 

```
About us
|--- What we do
|--- Start migrating/using/
```

**Comment by janchild** [comment]
Starting to draft out section. 
Breaking tickets up into bite-sized chunks so we can publish iteratively. 
Met with Jeff. Working on preliminary shape of page. 

Work is continuing next sprint in ticket #1337
