### ISSUE TITLE
Resolve lint errors across the codebase

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon-for-ibm-dotcom-website#1152]
## Detailed description

With a linter and formatter installed after #1150 there are a number of fixable lint and style issues

## Steps to reproduce the issue

run the `lint` npm script to show the linter output

## Additional information

![image](https://user-images.githubusercontent.com/8265238/130495484-7e627bde-f8d1-4420-b386-c36fd8f27497.png)

#1150 installed the packages for linting and formatting, and the newly identified issues now just need to be fixed. My concern is just with the timing on when to push the fixes so that the impact of the changes on any ongoing work is minimized

- All PR's must be merged before running this job.

**Comment by jeffchew** [comment]
Believe this may have been fixed after adding auto linting.
