### ISSUE TITLE
[Beacon] page placement, update content, comms for launch 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1157]
This issue has been recreated in the Becaon for ibm.com repo.  [Issue 28](https://github.com/IBM/beacon-for-ibm-dotcom/issues/28)

### Task 

- Determine how this page is available. On site? And if so, where?
- Page that talks about browser extension and CLI tools 
- Anything else that needs to be updated from original content pass, based on feedback from early adopters
- Communications for launch

-----

This work was previously documented here: 
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5637

Design a page where IBM.com application owners can come and enter an URL to run a report using Beacon to see the level of compliance. For now, the report will be rendered as n iframe on the page.

**Comment by RobertaJHahn** [comment]
Closing this issue as it has been recreated in the Beacon repo.
