### ISSUE TITLE
Website [Homepage] content exploration

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1164]

**Comment by IsiImoisi** [comment]
- Lead-in Sentence:
Carbon for IBM.com is the open-source design system for IBM.com’s web experiences.
Carbon for IBM.com consists of working code, design tools, and resources for page owners, designers, and developers creating pages for the IBM.com website.
Carbon for IBM is the open-source design system for everyone creating pages for an IBM.com website.
- Changed Getting started tag to "For You/ Resources/ Quick Select".

- Contemplating the "Dive Deeper" sections necessity.

- Added concept ideas for future photos.

- Rewrites for Contribution section include, but are not limited to:

Do you think there's anything we can add to make your or other users' experiences on this site better? Refer to the contribution guidelines and send us your ideas.
Want to make an impact? contribute your components and help us enhance the experience of all users on Carbon for IBM.
Do you want to make a difference? Contribute and add to the growth of Carbon for IBM.com?
Something you thought of can help other users on the site.

-Tagline rewrites are also under process and being refined.

**Comment by shixiedesign** [comment]
@janchild Actually Isi did have some alternatives proposed for "Getting started" heading. Please take a look if you can. Thanks!
