### ISSUE TITLE
Website [Homepage] New design wireframe

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1167]

**Comment by vinushad-ibm** [comment]
**Website Homepage Wireframe (work in progress)** 

- Added Hero image concept explorations

- Added Explorations of different content wordings to convey the right message

- Dropped verbs from "Getting Started" section 


**To do**
- Continue exploring hero image, content/wording expressions
- Explore the addition of quick links
- Find feasible ways that updates can be displayed on the home page

URL: 
https://ibm.box.com/s/3ilcgwip8twu5yoveogruywq90zi4yd3

**Comment by shixiedesign** [comment]
## Feedback

**Lead space**
1. Potentially CTA (call to action) on image, or move lead in sentence to above or over the image. 

**Getting started**
1. Consider different heading. Designing & developing also apply for returning visitors @IsiImoisi-ibm 
2. We might not want to point people to "Contributing" at this time
3. Potentially point people to [Standards site](https://www.ibm.com/standards/web/). Need a call to action & some context to explain what it is. If it's a bit lower down, it can also be one band. 

**What's new**
- Ask Jeff how realistic it is to import Slack messages? & how automatic.
- Consider a manual, simpler approach. List 3-4 items of the latest release, include link to Release notes page (release notes in github) to read more

Please look for places for these content: 
- Blog post (Ari's, Jeff's, [Color](https://medium.com/carbondesign/because-colors-are-beautiful-52dd4cc39f09), Jan also have a couple in the works) 
- Medium accounts we can pull from: https://medium.com/carbondesign & https://medium.com/design-ibm

Why Carbon

**Comment by vinushad-ibm** [comment]
**Homepage redesign explorations** 

- Created a CTA in the hero image that leads to the what's new section
- Visual design explorations and moodboards for the images associated with the different sections
- Variations in wording and content for the headings and body
- Created a separate section for community resources 
- Created a new section for IBM web standards 
- Separate section for articles and case studies 

**File:**
[Homepage Redesign (Carbon for IBM.com)Ver2.xd.zip](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/files/7287493/Homepage.Redesign.Carbon.for.IBM.com.Ver2.xd.zip)
