### ISSUE TITLE
Website [About: Steps to adopt] Page refresh 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1172]
Current page is not answering the question "how to adopt Carbon for IBM.com" very well. A few issues to callout: 
1. "Overview" section repeats what we are. Doesn't belong under the "adoption" topic
2. "What's included" conflicts with the other page "What we provide" 
3. "Choosing the right path to adoption" is a very important. We are getting Slack channel questions all the time about what's our relationship with AEM. This info should be clarified in this section. 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/5186f454-dd51-4ded-a937-4091d93e0d7a)

### Task

A content overhaul of this page is needed.

**Comment by janchild** [comment]
This ticket has already been partially addressed, and the remaining work is captured in #1168 and #1137.
