### ISSUE TITLE
Website [Images: Use of images] add link to Standards site 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1179]
On our component page [Images](https://www.ibm.com/standards/carbon/components/images), 

we should add a mention of the Standards site [**Page layout design**](https://w3.ibm.com/w3publisher/ibm-web-standards-external/standards-mandatory/page-layout-design) / Use of images 

Possibly via an Aside element. TBD based on the outcome of Component template work https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6846

**Comment by janchild** [comment]
Review with the team today and the vote was for the Aside with `IBM Web Standards` as the bold heading. Here is a screenshot.

![Contextual link to Web Standards](https://user-images.githubusercontent.com/44503588/133632098-2d3b2373-c7f6-4ab2-918d-71e8648170d4.png)
