### ISSUE TITLE
Website [Cards] update page images to show tags at the bottom of the card

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom-website#1211]
### Objective

Card (default) component recently got an update: the tags are now moved to the bottom of copy. Currently in the [Cards page](https://www.ibm.com/standards/carbon/components/cards#card), we still have 1 example image of Card showing tags above copy. This image needs to be replaced.  

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/160d29ba-839e-4b3e-87d7-efff61dcbceb)

### Useful resources

- Design page mockup using [Gatsby theme resources](https://carbondesignsystem.com/designing/design-resources/#gatsby-theme-resources)
- Create images **strictly** using Image production guidelines. Find sketchfiles from same link above 
- Create thumbnail image on the Components overview page - use the master Sketch work file [here](https://ibm.box.com/s/hyzeqfb7zqov1j3es4p6kplr6r15flat) to get started.
- For general contribution - Please visit the [Contributing page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/overview) for information and process detail.
- For Markdown best practices - Please visit the [Production guideline](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Carbon-for-IBM.com-Production-guidelines) to learn more.
- To setup the local build of the website, follow [Website edits via terminal](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Website-edits-via-Terminal)
- **Final Designs Box folder link:  https://ibm.ent.box.com/folder/95514001950?s=hgvu48r1fv2ga2h0yn3qshrtxjc71vch**

#### For how to create and submit PR 
There are several ways to submit a PR. Use whichever method you are comfortable with: 

1. [Using command line / Terminal](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/docs/developing.md#submitting-a-pull-request)
2. [Using VS Code](https://ibm.box.com/s/tf2gixqdng0s6v1xp7t49ddzasb3mvvy1)
3. [Using Github UI](https://github.com/carbon-design-system/carbon-website/wiki/Editing-Creating-a-PR-through-github.com-UI)

**Comment by shixiedesign** [comment]
Hey @RichKummer I imagine this will be the easiest for you because you should have the file to this image. Lemme know if you have any questions.
