### ISSUE TITLE
Website [Masthead, login] update with new login design

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom-website#1213]
### Objective
Follow on of https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7237

Current [Masthead page](https://www.ibm.com/standards/carbon/components/masthead#masthead-with-level-0) contains outdated example images. Since the login button's update, we need to update these example images. 

**Old:** 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/892989d5-5e29-4d84-a447-5eeac07b4dd1)

**New:** 
[TBD]

### Useful resources

- Design page mockup using [Gatsby theme resources](https://carbondesignsystem.com/designing/design-resources/#gatsby-theme-resources)
- Create images **strictly** using Image production guidelines. Find sketchfiles from same link above 
- Create thumbnail image on the Components overview page - use the master Sketch work file [here](https://ibm.box.com/s/hyzeqfb7zqov1j3es4p6kplr6r15flat) to get started.

- For general contribution - Please visit the [Contributing page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/overview) for information and process detail.
- For Markdown best practices - Please visit the [Production guideline](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Carbon-for-IBM.com-Production-guidelines) to learn more.

- To setup the local build of the website, follow [Website edits via terminal](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Website-edits-via-Terminal)

#### For how to create and submit PR 
There are several ways to submit a PR. Use whichever method you are comfortable with: 

1. [Using command line / Terminal](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/docs/developing.md#submitting-a-pull-request)
2. [Using VS Code](https://ibm.box.com/s/tf2gixqdng0s6v1xp7t49ddzasb3mvvy1)
3. [Using Github UI](https://github.com/carbon-design-system/carbon-website/wiki/Editing-Creating-a-PR-through-github.com-UI)

**Comment by oliviaflory** [comment]
Hey @skuruvil and @shixiedesign I found my Sketch file containing the [Masthead images](https://ibm.ent.box.com/folder/91877542962) and uploaded all to Box. Unfortunately I didn't note within the file which ones were the final images, but we could likely figure it out. 

**_Note:_** These images were created created _before_ the [Image production guidelines] were available from the Carbon team, so the artboard and image sizes will likely not match up.

**Comment by skuruvil** [comment]
You can find the Sketch file here 
https://ibm.box.com/s/dgf5t4g20u0z81vyykmpstitvhv9x2cj
