### ISSUE TITLE
Website [Masthead] Add guidance for when to use L0 and L1

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1227]
### A few variations of masthead is being misused

L0 default
L0 with platform
L1 

A lot of pages with L0 with platform should instead be using L1: 
- https://ibm.com/cloud/go-hybrid

### Some guidance top of mind (not all missing guidance are captured here)
- Navigation should be labeled with nouns, not verbs, so it's like geographical locations. 
- Platform name at the moment is only reserved for IBM Cloud. Not even IBM Security or Watson
- L1 is for all Topics (a topic is Security, Watson, Supply chain etc)

**Comment by RobertaJHahn** [comment]
The latest proposal allows for QRadar and other items are allowed to be in the L0.  The rule is flexible.  This issue can be closed.  It is outdated.
