### ISSUE TITLE
Website [Design kits] Page content rewrite pt1

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1232]
Re-structure the page in anticipation for updated design kit release

PR in progress: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1334

**Comment by janchild** [comment]
Reviewed with @oliviaflory Nov 3. Her work for https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/1319 was rolled in here, and Olivia and Jan reviewed and finalized together.
