### ISSUE TITLE
Website [Table of contents] Add content recommendations for TOC labels

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom-website#1280]
1. ### Add content guidance for the Table of contents labels 

An adopter asked:
> When using the Table of Contents, is the standard to have a matching heading on the right side of the content to match the TOC label? I didn’t see a reference in the design specs

Olivia had done some internal [research](https://ibm.ent.box.com/notes/735621982349) and made some recommendations for the labels while designing the horizontal version of the Table of Contents:
- Anchor link (TOC) labels and section headlines should be the same, or at least be a shortened version of the section headline
  - Label: People; Section: Forward thinkers ❌
  - Label: Clients; Section: Client success stories 🆗
  - Label: Connect; Section: Connect with IBM ✅

Horizontal:
- Label can match the Section or Content block headline
- Horizontal TOC is best suited for shorter labels
![Screen Shot 2021-10-18 at 3.51.44 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/06b25e75-cc4c-447a-94c2-a3d6096a9424)

Vertical
- Label generally matches, or is a shortened version of the Content block headline
- Vertical can accommodate multi-line label, and therefor can generally match the Content block headline.

![Screen Shot 2021-10-18 at 5.06.00 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/7a3f39d6-efd1-416a-9a2c-1f873e2589fd)

### 2. Update images
Some of the images on the TOC page are not showing the correct active section, which is confusing and doesn't show how the TOC functions accurately. 
![Screen Shot 2021-10-18 at 4.54.28 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/b0f768e2-0e64-4a91-9ba7-b57eab0915eb)

### 3. Behavior section?
It might be worth adding in the expected behavior of the TOCs, I've seen a few examples of live pages where the Horizontal TOC is used and the L1 doesn't scroll out of view like it's intended too.

**Comment by shixiedesign** [comment]
For vertical ToC, also need to add: 

Recommended to have a max of 7 items. This is because too many ToC items cause the ToC to become taller than screen height, and resulting in a double scroll. ToC should never extend more than screen height for it to be effective and sticky on page.
