### ISSUE TITLE
Update website's Contributing / Documentation page with the wiki page "Production Guideline"

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1285]
### Current
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Carbon-for-IBM.com-Production-guidelines

Mostly useful for our own team. We want to have a documented & standardized way of updating the website. 

### Task

- Deprecate the above wiki page, and consolidate Website production guidelines on [Contributing / Documentation](https://www.ibm.com/standards/carbon/contributions/documentation) page. 
- Name of the page could be potentially changed too. eg. Contributing / Usage guidance 

#### Notes

Should especially get rid of all the image making guidances in favor of https://carbondesignsystem.com/designing/design-resources/#gatsby-theme-resources

**Comment by shixiedesign** [comment]
@oliviaflory we should discuss some of these. Maybe you'd prefer to close them next year.

**Comment by oliviaflory** [comment]
[file naming guidelines](https://ibm.ent.box.com/notes/809809419456?s=xlq4romcyp50lnvwuaagyzzbmmesuxen) Note, these might be out of date, so we should review and update to current when addressing this issue.

Previously documented in #987
