### ISSUE TITLE
Website [Homepage] Content sweep

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1321]
I started the draft of homepage content, but needs the magic touch from Jan! 
https://ibm.ent.box.com/notes/878890487921

Jan's updated [Sketch file with content in place is here](https://ibm.ent.box.com/folder/149301389759).

**Comment by janchild** [comment]
@shixiedesign I've made a first pass through of the content. I updated the Box note but I've also created a copy of your Sketch file because I needed to see how the words looked in place. The [Sketch file is here](https://ibm.ent.box.com/folder/149301389759).

**Comment by shixiedesign** [comment]
Moving `The foundations` down might be viable but hard to tell for sure. My gut feeling is that these foundational links should be exposed earlier because we mostly hear people being very confused about who we are, and less on where to find stuff.

**Comment by janchild** [comment]
@shixiedesign I agree. It makes sense to me either way! Can we get this in?
