### ISSUE TITLE
[Lead space, video] Update page & content guidance

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1323]
### Details
- Page needs update to add this new feature 
- Follow current build: only discuss the one current option

### Notes from design reviews: 

When adding video to Lead space, there are two categories of design intent: adding video for ambiance, or adding video to provide information. 

**When adding video for ambiance**, the video should not contain information critical for users to complete their goal on page. The video should be on autoplay, loop, and stops at 5-10 seconds. 

**When adding video to provide information** in the lead space, it is recommended that the video should not be on autoplay, and requires the user to interact with it to explicitly express interest. In this case there should be a large play button on the right hand half of the lead space, overlaid on where the video would play. 

In any case, if it is critical for the video to autoplay, it must stop at 5-10 seconds. 

No audio is allowed. 

### Useful resources

- Design page mockup using [Gatsby theme resources](https://carbondesignsystem.com/designing/design-resources/#gatsby-theme-resources)
- Create images **strictly** using Image production guidelines. Find sketchfiles from same link above 
- Create thumbnail image on the Components overview page - use the master Sketch work file [here](https://ibm.box.com/s/hyzeqfb7zqov1j3es4p6kplr6r15flat) to get started.

- For general contribution - Please visit the [Contributing page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/overview) for information and process detail.
- For Markdown best practices - Please visit the [Production guideline](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Carbon-for-IBM.com-Production-guidelines) to learn more.

- To setup the local build of the website, follow [Website edits via terminal](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Website-edits-via-Terminal)

#### For how to create and submit PR 
There are several ways to submit a PR. Use whichever method you are comfortable with: 

1. [Using command line / Terminal](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/docs/developing.md#submitting-a-pull-request)
2. [Using VS Code](https://ibm.box.com/s/tf2gixqdng0s6v1xp7t49ddzasb3mvvy1)
3. [Using Github UI](https://github.com/carbon-design-system/carbon-website/wiki/Editing-Creating-a-PR-through-github.com-UI)

**Comment by ljcarot** [comment]
@dragosRistici Can this issue be closed? cc: @oliviaflory

**Comment by oliviaflory** [comment]
@ljcarot I haven't heard back from Dragos, but this guidance for video and the new background media feature has been added to the Website yet. I'll add it to our backlog for a future sprint.

**Comment by oliviaflory** [comment]
merged!
