### ISSUE TITLE
[Lead space, video] Content table update

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1324]
### Details 
- Content table needs an update
- Need to add a row "Video", optional, and has to have a Kaltura media ID

**Comment by JBrandwine** [comment]
[Update leadspace [content guidance table].mdx #1378](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1378)

**Comment by oliviaflory** [comment]
This is completed
