### ISSUE TITLE
Website [Homepage] Make updates based on the new designs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom-website#1330]
#### Overview
Carbon for IBM.com homepage is outdated. Internally we barely pay attention to it anymore because we click right pass it. But to our adopters, especially first time visitors, the homepage is painful and unhelpful. 

#### Detailed description

Root working folder: [IBM Digital Design Squad / Design / Website / Homepage](https://ibm.ent.box.com/folder/148570997952?s=1imq24pxvca9w9l714ln5sweocvcj83e)

- Content: https://ibm.ent.box.com/notes/878890487921
- Image assets: https://ibm.box.com/s/dpgwrlwnli9ekv5s55ilr0xfj7726qpj
- Design & spec: https://ibm.ent.box.com/folder/149301389759

#### Additional information
- [Homepage refresh epic](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/1163)
- [Design specs issue](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/1320)

#### Acceptance Criteria
- [ ]

**Comment by shixiedesign** [comment]
Sneak peak! Will be picking 1 of below: 
![image](https://user-images.githubusercontent.com/15144993/139793979-64a01152-5134-413b-a035-400dd7236dcb.png)
