### ISSUE TITLE
Website [Universal Banner] New webpage for new component

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom-website#1333]
### Objective

Provide Carbon for IBM.com adopters the most up-to-date best practices and guidance they need to adopt Carbon for IBM.com.

### Useful resources

- Design page mockup using [Gatsby theme resources](https://carbondesignsystem.com/designing/design-resources/#gatsby-theme-resources)
- Create images **strictly** using Image production guidelines. Find sketchfiles from same link above 
- Create thumbnail image on the Components overview page - use the master Sketch work file [here](https://ibm.box.com/s/hyzeqfb7zqov1j3es4p6kplr6r15flat) to get started.

- For general contribution - Please visit the [Contributing page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/overview) for information and process detail.
- For Markdown best practices - Please visit the [Production guideline](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Carbon-for-IBM.com-Production-guidelines) to learn more.

- To setup the local build of the website, follow [Website edits via terminal](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Website-edits-via-Terminal)

#### For how to create and submit PR 
There are several ways to submit a PR. Use whichever method you are comfortable with: 

1. [Using command line / Terminal](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/docs/developing.md#submitting-a-pull-request)
2. [Using VS Code](https://ibm.box.com/s/tf2gixqdng0s6v1xp7t49ddzasb3mvvy1)
3. [Using Github UI](https://github.com/carbon-design-system/carbon-website/wiki/Editing-Creating-a-PR-through-github.com-UI)

**Comment by oliviaflory** [comment]
## Universal banner draft

Besides the copy and language I would love some feedback on:

### Modifiers section
I am considering using the mini component template to show the image sizes (small and large options)

However, I'm not sure it's obvious enough what has changed.

### Behaviors section
**Small breakpoint**
The image is showing the small breakpoint, does it look a little odd floating on its own? The banner artwork is currently at exact size 320px.

Note: The production guidelines do not yet have a mobile device or browser mock up like the browser bar in the first image.

### Content guidance
I need to go through Jonathan's current guidance on other components and try to figure out the numbers for universal banner, there are so many optional pieces there might be a range...

[Universal banner component template.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/files/7695539/Universal.banner.component.template.pdf)

**Comment by RichKummer** [comment]
**Modifiers section**
* Personally, I would go with the full image comparison that you have in your github comment over the mini versions - I think it's clearer what differences there are. Designers may want to see that level of detail so they have an idea of what image asset to use. If we were planning to have a ton of variations, maybe it would be different, but with two I think we can show both in the image. If you decided to use that image instead, I would add a reference or label to the image to show which modifier is which.

If you decided to go with the mini version, I would follow Jan's advice and fade back the elements that are not the Universal banner. At a glance, I'm not sure what I should be focusing on.

**Behaviors section**
* I think the image might work better if you present a masthead and lead space below the Universal banner, but at 50% opacity. You don't need to show the full lead space, I think just enough to get the idea. I think it solves the floatiness by adding some context, and it would clarify that it stays at the top on mobile.

**Comment by oliviaflory** [comment]
Completed with #1414
