### ISSUE TITLE
Website [Designing] Include more guidance 

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-for-ibm-dotcom-website#1354]
This issue is to capture the work to build out the Designing page with content that will get designers familiar with core guidance. 

We had a [preliminary draft of some additional content](https://www.notion.so/carbondesignsystem/Get-started-551d0ebaa04c4abf9a3b40770993b428) here. 

Some additional thoughts from Shixie:

```
|--- Installing design kits
   |--- Sketch kit
   |--- Figma kit
|--- Learn about the foundations (mostly inherited unchanged except additional restrictions in below)
   |--- Grid
   |--- Typography  
|--- Dotcom design principles (...making these up at the moment...Wonil had some drafts)
   |--- Content first 
   |--- Expressive (brave? avant garde? lol) (Link to expressive styling)
   |--- Thoughtful and accessible (Link to accessibility requirements)
   |--- Focused on where the user might be in the moment of their journey. (Link to Essential Experiences)
|--- Additional info? 
   |--- Tutorials
   |--- Join our Slack 
```

There were some early drafts of Dotcom design principles from Wonil that need to be reviewed also. @shixiedesign could you please add the links? Thanks!

**Comment by shixiedesign** [comment]
Didn't find Wonil's document, but found this interesting Duo dyads 
https://ibm.box.com/s/byjqmb46z4qe3ik53aevbb6h9f5ffflo
