### ISSUE TITLE
[Support] Continue Chatbot content prep for TIPSBot:  follow-on to issue 1365

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom-website#1383]
#### Overview
This issue is to cover the work involved in preparing the content for the TIPSBot. 

#### Additional Information
- follow-on work from issue #1365

**Comment by JBrandwine** [comment]
Base questions and training questions can be found here:

https://ibm.box.com/s/dcemb93mid37cwll1ewnhuxpi56bf4et
