### ISSUE TITLE
Website assets: Continue proposal for Box folder organization:  follow-on from 1327

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom-website#1385]
This ticket is to cover the implementation of the proposal that was created in #1327. 

- [ ] Set up the new folder structure in Box
- [ ] Copy items into each folder
- [ ] Identify what's missing and reach out to team members to get the assets. 

-----

### Proposal for Box folder organization

The plan will be for the team to consider the proposal, and determine which direction to go before making any changes in Box.  

@IsiImoisi-ibm Excel is probably good to use for this exercise. 

A couple of pointers of some things we know we want:

- There are a lot of extra folders at the top level of `Website` so you may want to create a subfolder of `Website pages and images`.  

- There should be folders that map to the current website. So, document folders for left nav items and then the pages within each of these sections. 

- You can see everything here: `Website images` box folder: https://ibm.ent.box.com/folder/50861620698?s=3mysyf8bdkdo8u2h5baqhphzgnfjlt65

- Designers will be including both the source file (Sketch, Illustrator) as well as the final uploaded images in these folders. 

If you have any questions along the way, you can ask @oliviaflory or @janchild.

### Identify missing images and source files

As a second part to this work, we need to check what images are on the website that are not included in the current Box folder structure. 

You'll need a list of images that are currently on the website, so that you know when you've got everything (both source and final images). Excel is probably good for this cataloging exercise. 

#### Additional Information
- follow-on from issue(s):  #1327

**Comment by IsiImoisi-ibm** [comment]
Status Update:

### Completed:

- [X]  Set up the new folder structure in Box
![Website pages and images folder proposal](https://user-images.githubusercontent.com/84865950/145241298-f82e4908-d7f6-4962-8712-8a64f2697b31.png)

-All final images are uploaded to their respective folders

### Working on:

-Currently hunting down Sketch/ Illustrator files 
-Polishing off an Excel sheet

**Comment by IsiImoisi-ibm** [comment]
Status Updates:

Copied items into all folders
Made an excel sheet to break down what's missing and what isn't.

**Comment by IsiImoisi-ibm** [comment]
Status Update:

- [X] Set up the new folder structure in Box
- [X]  Copy items into each folder
- [X]  Identify what's missing and reach out to team members to get the assets.

Posted a message to the digital-design-designers so the respective persons can post the missing image sources to the folders.

**Comment by ljcarot** [comment]
@isilmoisi @janchild @oliviaflory Can this issue be closed from last sprint or is there still work to do?

**Comment by oliviaflory** [comment]
Yes, I believe this is completed, @IsiImoisi-ibm sent out these instructions on the designer channel on Dec 10


[Image information breakdown](https://ibm.ent.box.com/file/894162565804) What images are missing

[Website pages and images](https://ibm.ent.box.com/folder/151141006426) New website folder structure
