### ISSUE TITLE
Website [Tutorial content] Carbon foundations transcript

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-for-ibm-dotcom-website#1394]
We need to re-record some of our existing tutorial content to bring it up to date.

There is an excellent tutorial about Carbon foundations but it contains some content that is out of date and makes it impossible for us to use it as a reference. You should be able to get to it from one of these two links:

- https://ec.yourlearning.ibm.com/w3/series/10148614?layout=grid0
- https://ibm.ent.box.com/s/n21hgzxmfckzymjvpymly6phxvt7feyw

This ticket is to cover the first step of the work in creating content for the next version:

- [ ] Write up a transcript of the existing content
- [ ] Create a deck that includes the content shown in the Webex (you can skip the slides that are purely about the Expressive theme). 

From here, we can edit out the pieces that are not needed.

**Comment by IsiImoisi-ibm** [comment]
- [X] Write up a transcript of the existing content


[Digital Design Summit Webinar 1_ Carbon foundations.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/files/7722879/Digital.Design.Summit.Webinar.1_.Carbon.foundations.pdf)

[Digital Design Summit Webinar 1_ Carbon foundations(No expressive theme).pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/files/7722880/Digital.Design.Summit.Webinar.1_.Carbon.foundations.No.expressive.theme.pdf)

**Comment by IsiImoisi-ibm** [comment]
The previous deck has been located:
[Uploading Carbon-for-ibm-dotcom-design-deepdiver-1--1.0.0.pdf…]()

**Comment by IsiImoisi-ibm** [comment]
Original deck found:

[Carbon-for-ibm-dotcom-design-deepdiver-1--1.0.0.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/files/7780723/Carbon-for-ibm-dotcom-design-deepdiver-1--1.0.0.pdf)

**Comment by ljcarot** [comment]
@isilmoisi-ibm Can you please let us know when this issue is done? cc: @jeffchew @oliviaflory

**Comment by IsiImoisi-ibm** [comment]
It has been finished. @ljcarot
