### ISSUE TITLE
Content model: Universal banner component

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-for-ibm-dotcom-website#1416]
This ticket is to track the work @JBrandwine is doing to help decide on the best approach for laying out the variants on the Universal banner page.

**Comment by oliviaflory** [comment]
@JBrandwine Here are the image and character count (in the PDF) references for you!
![2:1_928x464px](https://user-images.githubusercontent.com/45692622/147127388-155b0373-aa5c-4d32-a005-0a0e9b39b843.jpg)

[universal-banner--specs.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/files/7764050/universal-banner--specs.pdf)

**Comment by JBrandwine** [comment]
Please see attached. I've also added it in its own in the [master content model spreadsheet](https://ibm.box.com/s/2drh0lhqrd8eo5tfc8ru46kdp8ckuu1c).
[Attachment: Universal banner spreadsheet](https://app.zenhub.com/files/202376156/9bc09c5f-b004-4ec5-85d4-4df5864bf330/download)

**Comment by janchild** [comment]
Thanks, @JBrandwine! Taking a look now. 👀

**Comment by oliviaflory** [comment]
This has been completed and is added to #1414
