### ISSUE TITLE
SSL cert issue: SSL cert not working on carbon environment on public web

### ISSUE THREAD

**Issue by mosesharrisjr** [carbon-design-system/carbon-for-ibm-dotcom-website#1441]
### Description

Just giving the team a heads up.  I googled "ibm carbon footer" and was taken to http://carbon-for-ibm-dotcom.mybluemix.net/.  I was told it's a lower test environment that may be decommissioned.  Either way, it's being crawled and indexed.

<img width="842" alt="Screen Shot 2022-01-26 at 11 24 21 AM" src="https://user-images.githubusercontent.com/12969233/151214882-29a0bbed-62df-4c52-8bb5-ff48908e0d75.png">

<img width="465" alt="Screen Shot 2022-01-26 at 11 10 38 AM" src="https://user-images.githubusercontent.com/12969233/151214889-2fc3e671-1193-4da0-825e-90ed6512c90e.png">

Your team does great work. Thanks for all you do.

### Page(s) impacted

the http://carbon-for-ibm-dotcom.mybluemix.net/ domain

### Browser

Chrome

### Steps to reproduce the issue (if applicable)

1. open http://carbon-for-ibm-dotcom.mybluemix.net/
2. check the address bar. 

### Code of conduct

- [X] I agree to follow this project's [Code of conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/main/.github/CODE_OF_CONDUCT.md).
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues) for duplicate issues.

**Comment by ljcarot** [comment]
mybluemix.net is being sunset so this will be resolved this year.
