### ISSUE TITLE
[Homepage]: Storybook icons look bigger than others on homepage

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom-website#1455]
### Description

Mike pointed out the Storybook icon seems bigger than the 32x32 canvas. 
<img width="830" alt="Screen Shot 2022-02-03 at 12 54 47 PM" src="https://user-images.githubusercontent.com/45692622/152885368-2acaa0c5-dc64-489f-ae46-f051b790d336.png">

This page has storybook icon in mini cards, possibly reference as the size
Reference: https://v11.carbondesignsystem.com/data-visualization/complex-charts/#alluvialsankey-diagrams

### Page(s) impacted

Homepage

### Browser

Chrome

### Code of conduct

- [X] I agree to follow this project's [Code of conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/main/.github/CODE_OF_CONDUCT.md).
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues) for duplicate issues.

**Comment by mjabbink** [comment]
Not look too big! They ARE too big.

**Comment by mjabbink** [comment]
@jeffchew @oliviaflory This should not be a stale issue. Should be a fixed issue by now I reckon.

**Comment by oliviaflory** [comment]
Merged and complete in https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1490
