### ISSUE TITLE
[React wrapper] Website documentation

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom-website#1491]
### User story
As a Carbon for IBM.com developer, I need to review and update the React wrapper documentation on the Carbon for IBM.com website to ensure documentation and usage are clear for adopters.

### Additional information
Places to consider adding messaging:

#### Developing
**Get started**
- Choose your framework

**Frameworks**
- React wrapper any updates to this section?
- Add a tab for React wrapper? Or change React tab to React wrapper and update documentation on how to use React wrappers
- Do we need documentation on how to migrate to React wrapper from native React?

**Comment by RichKummer** [comment]
[**Mural brainstorm link**](https://app.mural.co/invitation/mural/carbonforibmcom3039/1655819368336?sender=uf83bc0b1e31118868ab69626&key=a25a7fef-8c2c-4958-aac4-e5523c9663ef)

**Comment by ljcarot** [comment]
Finished
