### ISSUE TITLE
[Website] Content item

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom-website#1589]
Content item received numerous changes in v2, including a new orientation modifier for horizontal/vertical.

**v2 guidance content:**
- [ ] Update details on usage (content block going away, etc.)
- [ ] New info on orientation modifier for horizontal/vertical
- [ ] New information on variants for `media`, `percentage`, `logo`, `large icon (pictogram, app logo)`. Include which variants work in which orientation. Guidance on length for `percentage` etc.
- [ ] Note that `pictogram item` was previously its own component in v10
- [ ] Aspect ratio options for `media` for each orientation
- [ ] Placing `content item` in a collection (vertical or one by one in a row)
- [ ] Use lower case for component names.

**v2 media assets:**
- [ ] Need to update all three existing images
- [ ] Need new images to communicate new variants and orientation modifier. Any Do/Do not guidance as well

**Additional enhancements:**
- [ ] GIF animation to show the variants and orientation options
- [ ] GIF animation to show how `content item` behaves in a collection

**Comment by oliviaflory** [comment]
Note: [CTA block & section](https://www.ibm.com/standards/carbon/components/cta-block-and-section#modifiers) have a nice diagram of content item types if we needed a quick image to repurpose (I might have the previous asset in Sketch to reference)
