### ISSUE TITLE
[Website] Universal banner

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom-website#1610]
Universal banner has some TBD changes for v2 that need to be discussed.

**v1 changes:**
- [ ] Update language in overview pointing users to `content group banner` when used in page content. 
- [ ] Include language around 4-column vs 8-column image.This is vague currently.
- [ ] Use lower case for component names.

**v2 guidance updates:**
- [ ] Any color scheme options added for v2 – need new modifier content
- [x] Potential name change we might consider

**v2 new images:**
- [ ] Any color scheme options would need to replace all five imagery to promote lighter color scheme
- [ ] If we include more color options (blue10, etc.) we need new image assets to illustrate these.
- [ ] New overview image for masthead?

**Comment by oliviaflory** [comment]
- [ ] Use [Component template](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/1668) for release for content updates
