### ISSUE TITLE
[Website] Expressive modal

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom-website#1616]
There's no planned changes to `expressive modal` in v2. There is an opportunity to answer key questions – the page itself has very little content or guidance.

**v1 guidance updates:**
- [ ] [Adopters have asked](https://ibm-studios.slack.com/archives/C2PLX8GQ6/p1637764138202300) in the past around centering the modal, we should provide more context here.
- [ ] Should clarify that the modal becomes scrollable if content does not fit into container.
- [ ] Should clarify that the expressive modal comes with a close button that removes the overlay. Clicking into the dark area dismisses the modal.
- [ ] The above can probably be adapted from Carbon core's Modal page.

**v1 media update:**
- [ ] Repurpose image in `lightbox media viewer` page to better reflect nesting content.

**V2**
- [ ] Remove use case image for large variant (does not reflect accurate usage

**Future enhancements:**
- [ ] The examples used only show a blank background below the dark area of the overlay. We should provide more in-context shots so it's clear how the modal appears over page content.
- [ ] The image assets do not convey the flexibility of `expressive modal` in the best way. We should consider new media assets or an animated GIF to help illustrate that content can be fed into the overlay in multiple ways.

**Comment by oliviaflory** [comment]
- [ ] Use the [Component template](https://www.ibm.com/standards/carbon/components/language-selector) for release for content updates
