### ISSUE TITLE
[Website] Lead space

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom-website#1618]
v2 brings a number of changes to `lead space`.

**v1 content updates:**
- [x] Include new modifier section to toggle gradient on and off. Need guidance for this.
- [x] Add gradient to Content guidance section. 
- [x] For `short`, clarify that body copy and button group do not appear.

**v1 media updates:**
- [x] Need to replace all ten images/GIFs to reflect the swapped button ordering and type update.
- [x] Need new image to display the gradient on/off.

**v2 content updates:**
- [x] Include new modifier information for heading type tokens.
- [x] Include guidance for highlighting word or words in the lead space heading (TBD).
- [ ] If we add an option for `background media` to drop below on all breakpoints for `lead space - centered`, we should write guidance for that (displaying a product screen for example). 
- [ ] If we add a 50/50 option, we will need new guidance for that.

**v2 media updates:**
- [x] Image displaying the optional gradient (one with photography, one with illustration).
- [x] Image(s) for highlighting word or words in the heading.
- [ ] If we add an option for the image drop in `lead space – centered`, we need to add a new image to show the difference.
- [ ] If we add a 50/50 option, we will need new image(s) for that.

**Comment by oliviaflory** [comment]
**Notes**
- Clarify background video (accessibility)
- Tag links needs to be addressed
