### ISSUE TITLE
[Website] Cards

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom-website#1621]
**v1 guidance updates:**
- [ ] Future state: add notification to the top of `Cards` page to indicate that `feature card` and `card in card` are separated into their own pages in v2. Include links to those page.

**v1 media updates:**

**v2 guidance updates:**
- [ ] Update Overview links to send users to `feature card` and `card in card` pages if they need a more prominent solution.
- [ ] Change reference to _CTA link_ 
- [ ] Update Pictogram content to cover the updated interaction (no hover reveal).
- [ ] Update content for `card link` to make the relationship clear. This will be a modifier on `card` used in a particular way at the end of `content sections`.
- [ ] Move `card` resource card to the top of the page.

**v2 media updates:**
- [ ] Update Overview image asset – use updated card (with icon to the right). Remove `card in card` and `feature card`. Instead use logo and static variant.
- [ ] Update Card anatomy image with v2 card.
- [ ] Update Card varying content image.
- [ ] Update Logo image with updated `card - logo` in v2.
- [ ] Update Logo Do/Do not image with updated v2 design.
- [ ] Remove GIF hover effect for `card - pictogram`
- [ ] Update Static Do/Do not images with updated v2 design.
- [ ] Update `card link` image with updated v2 design.

**Comment by oliviaflory** [comment]
## Component template for v2 website launch

### Variant assignment
- Default Olivia
- Pictogram Rich
- Logo Olivia
- Feature Rich
- Static Olivia
- Card in card Rich
- Link Olivia

Leave cards as a combined page for launch, will address separating variants/etc post Nov.


### Overview
- [ ] Description of the component
- [ ] Updated image of the component _only if the component has the `visual design change` tag in the issue_
- No anatomy image in this round

### Behaviors
- Only use if you can describe in words, no images

### Modifers
- Only use if you can describe in words, no images
- Example: Callout with media comes in a variety of colors

### Tips & techniques 
- Skip if the component page does not already include

### Resources
- [ ] Storybook links updated – WC leads
- [ ] Remove Sketch
- [ ] Remove Func spec

### Content guidance
- [ ] This must be accurate & updated

## Process
1. We will scope the issue as a team to determine severity of page lift
2. Pull component issue assigned to you and copy this component template into the body of the issue
3. Follow the above launch template and push to v2 feature branch
4. Create follow on issue  titled [Website] Component: X follow on and tag with `v2` `website` so we can add more details after launch
   a. Also consider tagging high priority ones (ie cards)
