### ISSUE TITLE
[Website] Content group

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom-website#1633]
The Content group page needs updates for v2

**v2 guidance updates:**
- [ ] Replace references to `content block` with `content section`.
- [ ] Remove `Content. block` from component description in JSON
- [ ] In Related components section, remove all but `card group`
- [ ] Consider a notification at the top indicating that multiple `content group-x` components were deprecated, but `content group` can be modified to achieve any of those.
- [ ] Use lower case for component names.

**v2 media updates:**
- [ ] Replace Overview image for new `card link` design
- [ ] Replace animated example GIF (this might take some time to re-do)

**Comment by oliviaflory** [comment]
### User story
We do not have the time or bandwidth to complete our usual documentation prior to the v2 launch, so this is the template we will follow to get the minimum viable content out for each component.

---

## Component template for v2 website launch

### Overview
- [ ] Description of the component
- [ ] Updated image of the component _only if the component has the `visual design change` tag in the issue_
- No anatomy image in this round

### Behaviors
- Only use if you can describe in words, no images

### Modifers
- Only use if you can describe in words, no images
- Example: Callout with media comes in a variety of colors

### Tips & techniques 
- Skip if the component page does not already include

### Resources
- [ ] Storybook links updated – WC leads
- [ ] Remove Sketch
- [ ] Remove Func spec

### Content guidance
- [ ] This must be accurate & updated

## Process
1. We will scope the issue as a team to determine severity of page lift
2. Pull component issue assigned to you and copy this component template into the body of the issue
3. Follow the above launch template and push to v2 feature branch
4. Create follow on issue  titled [Website] Component: X follow on and tag with `v2` `website` so we can add more details after launch
   a. Also consider tagging high priority ones (ie cards)
