### ISSUE TITLE
[Website] Guideline Spacing

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom-website#1644]
### Spacing token and scale

**Spacing token**
- [x] Are the code examples of "approved ways to syntactically apply spacing tokens" correct?? [Still correct in v2](https://ibm-studios.slack.com/archives/G02TA1VQ0KX/p1702490455088849)
- [x] Card and Content block example images is not very good (blurry)
   - [x] Above will all likely need to be updated for v2 as we will likely be changing all of the spacing logic 😭 

**Spacing scale**
- [x] Should we update to purple spacing scale like Carbon? It's easier on the eyes.

### Content component spacing patterns 
- [x] Dislike the usage of "pattern" here
- [x] Will need to rethink how we want to communicate the spacing logic for components in v2
   - [x] I think we'll have to have a page about how components fit together or "how to build a page"
   - [x] IMO each Content section, Content group, Content item should have their spacing logic documented ON their component page
   
### FAQ
- [x] Center – should we add that center is typically used for inside containers?
- [x] Percentages – is 5% grid margins still accurate in Carbon 11? Is it different logic with CSS grid package? _Percentage margins appeared in v9, but did not migrate to v10 or 11_
- [x] Padding vs margin. We don't want "here" as link. Re: CSS Box Model
- [x] IS THIS CONTENT EVERGREEN

### Support
- [x] Should support be a card link or text link? Ensure it's consistent throughout the website.

**Comment by RichKummer** [comment]
[Page design in Figma](https://www.figma.com/file/AaE0a6VVvSrMD9kppc8hFp/Website-updates-v2?type=design&node-id=879%3A346&mode=design&t=wWi9d9YfIfdS2WSf-1)
