### ISSUE TITLE
[Website] Guidelines Style models

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom-website#1657]
## V2

- Technically Docs model is not accurate / possible today, but we plan to add
- Jeannie to follow up with new grid docs at a later date
- Option to hide this page on launch

**Comment by jeanservaas** [comment]
@oliviaflory 

- see how you feel about cutting all of the screen region stuff

- i don't like the name "Product and docs model" — shixie originally had "Documentation model" but literally like ALL OF PRODUCT uses the left hand alignment, docs is just an outlier on [IBM.com](http://ibm.com/)... I think we should call it the Product model for clarity

https://www.figma.com/file/3txRSZaAvAIYpB4xyEP5KD/Style_model_docs?type=design&node-id=10%3A363&mode=design&t=xEi6iC1cgDpTDYR1-1
