### ISSUE TITLE
[Website] Developer Get started

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom-website#1674]
### Update content for Website v2
[Developing/Get started](https://www.ibm.com/standards/carbon/developing)
- [x] Remove all mentions of pure React package
- [x] Replace with React wrapper package?
- [ ] Is Summit content outdated at this point?
- [ ] Consider referencing how Carbon intros their [Getting started](https://carbondesignsystem.com/developing/get-started/) page

**Comment by kennylam** [comment]
React references removed in https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1696
