### ISSUE TITLE
[Website] Frameworks

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom-website#1675]
## Update Frameworks pages for v2

Developing / [Frameworks](https://www.ibm.com/standards/carbon/developing/frameworks/web-components)

### React tab
- [x] Remove

**Comment by kennylam** [comment]
React tab removed in https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1696
