### ISSUE TITLE
[Website] Other packages

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom-website#1676]
## Update Other packages page content for v2

Developing / [Other packages](https://www.ibm.com/standards/carbon/developing/other-packages)

This page might be worth updating / combining / replacing with the Developer / Resources page *new* #1656 
 
- [x] Remove all mentions of pure React package
- [ ] Should we add the CWC package to this page? Do adopters have to use CWC with C4IBM?

**Comment by kennylam** [comment]
> * Should we add the CWC package to this page? Do adopters have to use CWC with C4IBM?

There is a section on [this](https://www.ibm.com/standards/carbon/developing/frameworks/web-components#using-with-carbon-web-components) page that already addresses using CWC with dotcom components. Is it ok here or should we move it?

**Comment by oliviaflory** [comment]
> > * Should we add the CWC package to this page? Do adopters have to use CWC with C4IBM?
> 
> There is a section on [this](https://www.ibm.com/standards/carbon/developing/frameworks/web-components#using-with-carbon-web-components) page that already addresses using CWC with dotcom components. Is it ok here or should we move it?

Can't hurt to include CWC on both pages just to ensure adopters don't miss it? I don't have a good sense of how often people are visiting these pages but whatever you think!
