### ISSUE TITLE
[Website]: Favicon Guidance

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom-website#1759]
### User story

We need to address adding the favicon guidance to the Carbon for IBM.com website

#### Resources
- Diana S and Sam T have started some guidance for favicon usage in IBM products
   - https://ibm.ent.box.com/notes/1361499015900
- We should add the same or similar guidance to the Carbon for IBM.com site
   - Consider if it should be added to the w3 Standards site and/or the AEM site as well

#### Problems we are addressing
- Inconsistent usage of favicons across IBM.com
- Favicons not passing color contrast in dark mode

#### Favicons
1. Can teams choose to use an icon instead of an app icon? (solid color vs gradient)
2. What favicon would we suggest for the IBM homepage / default
3. This guidance suggests teams have control over their favicon, but I am not positive every page author does
   3a. aka this guidance might not be globally relevant
4. Do we want to link out to a medium article we didn't write for guidance on creating a favicon.ico file?

#### Browser tab labels
1. This guidance seems like internal strategy (gated) 
2. Does it belong on the Standards site on w3?
   2a. I don't actually know how teams control the page labels, is it within AEM? What about the Docs team? Is this something we'd have to approach each individual team with? 

### Acceptance criteria

- [ ] _{{State acceptance criteria}}_
- [ ] _{{State another}}_
- [ ] _{{And another}}_

**Comment by oliviaflory** [comment]
We will be reaching out to the Brand team to discuss publishing the favicon guidance on the Brand Center site as it spans both Dotcom and Product space, and possibly discuss the standardization of tab labels there as well

**Comment by mjabbink** [comment]
@oliviaflory @RichKummer @jeanservaas We need to get this up. Watson and others are implementing favicons left and right, all wrong. There is an issue here with the content and images that we need to polish. https://github.ibm.com/CDAI-design/pal/issues/1550#issuecomment-79672419

**Comment by mjabbink** [comment]
<img width="609" alt="Screenshot 2024-05-31 at 8 29 44 AM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/assets/32881239/c27cc5f9-bf20-4845-b2c1-b5d41a4319e0">

**Comment by mjabbink** [comment]
@oliviaflory  Let’s, please get this done in the next sprint or two, maximum.

**Comment by mjabbink** [comment]
I think this needs to go in C4IP.

**Comment by oliviaflory** [comment]
@mjabbink I will close this issue because we agreed to put it on C4IP, and it's been published! 

https://pages.github.ibm.com/cdai-design/pal/browser-tab-guidance

**Comment by mjabbink** [comment]
Yes, but we need to make an issue regarding updating images and some of the content structure. It currently does not use the intro and page anchor links for example.

**Comment by mjabbink** [comment]
@oliviaflory Any movement on this issue?

**Comment by oliviaflory** [comment]
Hey @mjabbink we asked Sam to make the updates to the images, I have an[ issue to track](https://github.com/carbon-design-system/ibm-products/issues/5408) in the Carbon for iBM Products board. I shared the [Figma file](https://www.figma.com/design/HwABG4DYk2m8q8atrjMW0E/Browser-tab-guidance?node-id=0-1&t=4UIV6c8nPjMDh2YO-1) with your comments with him. It looks like he is on vacation until July 1, so I will check in with him on timing when he gets back.
