### ISSUE TITLE
Conduct adopter research for the Help/FAQ page content update

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#261]
#### User Story

> As a Cupcake website content creator

> I need to: know what frequently asked questions our adopters have

> so that I can: consolidate them and present them on the FAQ page.

#### Additional information
- Issue #42 has the planning detail we need to conduct the adopter research.
- FAQ questions are consolidated via this [Airtable document](https://airtable.com/invite/l?inviteId=invUQQUVcYNJPrCwd&inviteToken=0abbd6c878f07746d5f58a079f635443d41e3cb8699ac384eb9cd869675d062d).

#### Acceptance criteria
- [ ] A list of the questions from the adopters collected.
- [ ] Update content approved by Wonil and Linda.

**Comment by JennySanchez** [comment]
**Note:** 
The Box note link to gather feedback from adopters around the different topics including components, resources, and overall general content on the website. 

https://ibm.box.com/s/cuhmld1kb6e1y70pjxqkl1gkhgvdpiaa

**Comment by ljcarot** [comment]
Adopter is looking for full built page examples of a page built in Carbon (for IBM.com).  He is PM for rebuilding Employment website on ibm.com

**Comment by JennySanchez** [comment]
FAQ for Patterns from @larahanlon2: 
https://ibm.ent.box.com/notes/724605583871

**Comment by JennySanchez** [comment]
Task title updated from Q4 to Q1 2021. We should prioritize the Adopter Research work in Q1 and move forward from there.

**Comment by JennySanchez** [comment]
This task is relevant and in prioritization.

**Comment by JennySanchez** [comment]
We will create proper Epic and issues when we are ready to set up Adopter research-related task, for now, it's no longer a priority, and the task will be closed.
