### ISSUE TITLE
Update Design Kit link to Design Kit Cloud Download (End of Q2) on the website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#483]
@JennySanchez commented on [Tue Apr 28 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2936)

> As an IBM.com Library website adopter 

> I need a way to download the Design Kit from the Cloud

> so that I can have the kit installed and do what I need to do efficiently.

#### Additional information
- @oliviaflory mentioned we will have the Design Kit download path from taking the adopters to the BOX folder to the Cloud download instead.
- Timeline: End of Q2

#### Acceptance criteria
- [ ] All Design Kit download paths and links on the website is updated.

---

@JennySanchez commented on [Wed Jun 24 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2936#issuecomment-648913082)

**Task Update:** Followed up with @oliviaflory earlier today and Design Kit Cloud download is not ready. 
@RobertaJHahn Can you help by moving this task to Sprint 20-14? Thank you.

**Comment by JennySanchez** [comment]
@oliviaflory Should we move this task to the backlog till it's ready?

**Comment by JennySanchez** [comment]
@RobertaJHahn Olivia had not heard any announcement about the cloud download is ready. Let's move this task to the backlog for further prioritization once the Design Kit Cloud Download is ready, please. Thank you.

**Comment by RobertaJHahn** [comment]
@JennySanchez Done

**Comment by JennySanchez** [comment]
@oliviaflory Any updates regarding the Design Kit Cloud download set up?

**Comment by oliviaflory** [comment]
@JennySanchez not yet, we were delayed in discussing with the Carbon team. Will add you to the meeting as optional when I schedule it

**Comment by JennySanchez** [comment]
Sounds good. Thanks, @oliviaflory!

**Comment by JennySanchez** [comment]
@RobertaJHahn I am going to keep the task issue open for now. 

@oliviaflory When you return in January, can you provide the status for Design Kit Cloud Download set up? If there's no movement, I'd like to close this task issue and we can create a new one when we have a better view of when it will happen.

**Comment by JennySanchez** [comment]
This task is relevant and in prioritization.

**Comment by JennySanchez** [comment]
**Task update:** Follow up with Olivia today and suggest we close this task issue if we are not ready.

**Comment by oliviaflory** [comment]
Closing this issue for now.

Based on some new conversations with the Carbon team, it's possible they will be adding expressive variants to Carbon core, which might make the expressive kit not needed. 
We may want to hold off on adding the kit via Sketch Cloud if we are potentially reducing the amount of expressive components and changing the expressive theme logic.

cc: @JennySanchez @shixiedesign

**Comment by RobertaJHahn** [comment]
Closing based on Olivia's comments.
