### ISSUE TITLE
Follow up with the Carbon Team on component demo window implementation - Target 1Q 2021

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#493]
> As a Cupcake website creator,

 > I need to know what we need to do to implementation and demo window feature to showcase the components

> So that we can be aligned with the carbon website and create a great browsing experience for our adopters.

#### Task

- [ ] Followed up via a [Git issue](https://github.com/carbon-design-system/carbon-website/issues/870) on the Carbon Gatsby Github and his comment is as follows.

![Screen Shot 2020-06-24 at 10.26.40 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/f11dbb56-5dde-4f11-802a-cfd3926b768d)

### Acceptance criteria

- [ ] Have an clear plan on the next step for demo window implementation.

**Comment by JennySanchez** [comment]
@RobertaJHahn This is a task for the website stream to do in the beginning of the Q4/October 2020.

**Comment by RobertaJHahn** [comment]
@JennySanchez Since this work is so far into the future, I have added the sprint 20-20 milestone (9/28/ - 10/09), but will do the remaining updates later.

**Comment by JennySanchez** [comment]
@RobertaJHahn Sounds great. Thank you!

**Comment by JennySanchez** [comment]
Reached out to Matt to find out if there are any priority updates.

**Comment by JennySanchez** [comment]
Matt mentioned he has no updates but asked me to add comments on the Carbon issue to get input from Vince and for everyone interested.

**Comment by JennySanchez** [comment]
No further movement from Vince and we will continue on doing follow up in 2021.
