### ISSUE TITLE
Create the design checklist for whenever we upgrading/updating Gatsby

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#629]
#### User Story

> As a `[user role below]`:
IBM.com Library Designer

> I need to:
follow all necessary steps when upgrading/updating Gatsby in the IBM.com Library

> so that I can:
not skip any important updates or thought the website is not functioning properly

#### Additional information

  - The documentation will be done in a Box Note that is included in the [Team Operation Processes folder](https://ibm.ent.box.com/folder/73421610286)
 - The documentation should identify design and website tasks for both pre and post Gatsby upgrade and update

#### Acceptance criteria
 - [ ] Have a documented list of design items to do whenever we upgrading/updating Gatsby
 - [ ] Determine how we can integrate this into our regular workflow

**Comment by JennySanchez** [comment]
@RobertaJHahn Do we have any existing checklist I can see as an example for me to create one for review?

**Comment by jeffchew** [comment]
@JennySanchez the engineers follow a **playlist** whenever we do releases: https://ibm.ent.box.com/notes/497596874716. It's probably not going to be as comprehensive for upgrading gatsby, but you can capture tasks this way.

**Comment by JennySanchez** [comment]
Awesome. Thank you for sharing, @jeffchew!

**Comment by JennySanchez** [comment]
This task is still relevant.

**Comment by JennySanchez** [comment]
This task is relevant and in prioritization.

**Comment by JennySanchez** [comment]
**Note:** Vince suggested using tools like Percy to do visual regression testing https://percy.io/.

**Comment by JennySanchez** [comment]
@RobertaJHahn Task will be closed. Based on the conversation with Jeff. We will no longer need to create the checklist for Gatsby update.
