### ISSUE TITLE
IBM Web Standard - v18 message implementation

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#685]
#### Objective

This task is for the dev team to implement the blue message bar on the IBM Web Standard website, so the adopters know when the v18/v19 will be sunsetting.

#### Note

- Design detail can be viewed via #673.
- The message bar will stay above the lead space on all website pages.
- The "View detail" tab will take adopters to the Get started/[Overview page](https://www.ibm.com/standards/web/ibm-dotcom-library/get-started) and please make sure it's landed at the "Legacy design systems are v19a, v18, and older (The sunset of the legacy systems will begin in the 4th quarter of 2021)" section (see reference below).

![Screen Shot 2020-10-08 at 12 04 32 PM](https://user-images.githubusercontent.com/45213839/95491190-e2b4af00-095e-11eb-983a-4ed0f69239b2.png)

- Sketch work file can be found [here](https://ibm.box.com/s/c4ypfbtcbdulp1x307rcm7qy2mz7a5j8).

(Blue message bar design)
![v18v19 sunset message design](https://user-images.githubusercontent.com/45213839/95103941-e34d0b80-06fa-11eb-846a-67f3ece6f065.jpg)

(Blue message bar specs)
![Spec](https://user-images.githubusercontent.com/45213839/95103954-e6e09280-06fa-11eb-8678-dbb081130965.jpg)

(Blue message bar color)
![Screen Shot 2020-10-05 at 11 08 01 AM](https://user-images.githubusercontent.com/45213839/95104103-12637d00-06fb-11eb-8d3b-cc06ebbac1fc.png)

#### Acceptance criteria

- [ ] The blue message bar is implemented on the IBM Web Standard Website.

**Comment by JennySanchez** [comment]
Hi @jeffchew, Check in to see if you need anything and how's the implementation going?

**Comment by jeffchew** [comment]
@asudoh added your name to this as it looks like you took this one on, thank you!

**Comment by RobertaJHahn** [comment]
@asudoh Did you take a look at this?  Can I close or should I move it to the next sprint?

cc:  @jeffchew

**Comment by JennySanchez** [comment]
@jeffchew Can you share the preview link here? I can help by taking a look as well.

**Comment by asudoh** [comment]
@RobertaJHahn There is a PR that is ready for review: #720

@JennySanchez The deploy preview can be found at: https://ibmdotcom-library.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/720/

**Comment by JennySanchez** [comment]
Hi @asudoh 

**When I view it via the deploy link provided above.** 

- The deploy link is not working for me (see screenshot below).

![Screen Shot 2020-10-28 at 5 15 30 PM](https://user-images.githubusercontent.com/45213839/97502497-381e2380-1941-11eb-9f19-c43b2eff82b0.png)

---

**When I view it via the link in PR #720.** 

![Screen Shot 2020-10-28 at 5 16 24 PM](https://user-images.githubusercontent.com/45213839/97502800-e2964680-1941-11eb-8663-5d5704c9956a.png)

- The first time it worked. The blue bar looked ok but when I clicked on the "View detail" button, it did not take me to the "Get started" page but an error page.

- When I tried to view it again via the preview link in #720, It took me to the Carbon for IBM.com homepage for some reason and I could no longer see the preview content.

![Screen Shot 2020-10-28 at 5 16 51 PM](https://user-images.githubusercontent.com/45213839/97502831-ed50db80-1941-11eb-9e13-0468d6606c17.png)

**Comment by asudoh** [comment]
@JennySanchez Thank you for testing it out!

![banner](https://user-images.githubusercontent.com/1259051/97507586-d30a1280-19c0-11eb-956d-d39ff0062d90.gif)

> when I clicked on the "View detail" button, it did not take me to the "Get started" page but an error page.

Looks that it's specific to our deploy preview environment, where URL referring to a directory yields to `404` (page not found) error instead of leading to `index.html` in the directory. Same URL under https://www.ibm.com/standards/web/carbon-for-ibm-dotcom works.

> When I tried to view it again via the preview link in #720, It took me to the Carbon for IBM.com homepage for some reason and I could no longer see the preview content.

Carbon core website removes the banner for future access once user acts on the banner. I did the same, but let me know if you think the banner should be persistent. You can reset such state with Chrome DevTools' Applications tab.

**Comment by JennySanchez** [comment]
Akira, Thank you for taking a look at the blue bar with me. As discussed, this Blue bar is for the [IBM.com Web Standard](https://www.ibm.com/standards/web/) website but not Carbon for the IBM.com website.

**Comment by JennySanchez** [comment]
@asudoh Do you need anything else from me before I move this task issue to the Done column?

**Comment by asudoh** [comment]
@JennySanchez Once the reviews of https://ibm.biz/BdqtN8 as well as one of #720 have been merged, we can close this issue. Thanks!

**Comment by JennySanchez** [comment]
Perfect. Thanks.
