### ISSUE TITLE
Content crafting and publishing: Contribution/Patterns Page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#686]
⏰ **NOTE: This task is set to be worked on in Sprint 20-22. If possible, we will start the task in Sprint 20-21.** ⏰

-----

#### User Story

> As an IBM.com Library adopter, 

> I need guidance on how to contribute patterns to the IBM.com Library,

> so that I can support the growth of the IBM.com Library. 

#### Additional information

- Work on the content by following the [publishing process](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj) as much as possible and as needed.
- Craft content based on the idealization outcome of the I[deation: Contribution Detail page](https://github.com/carbon-design-system/digital-design-ideation/issues/141) task on the ideation board.
- Create the website design with the Sketch App as needed and the Sketch publishing template can be found on the [BOX folder](https://ibm.box.com/s/ma72t84m75fvd3qqkyz8cm6gfx9b7vou). Once complete, save the revised Sketch file in the Guideline folder / sub-folder [here](https://ibm.box.com/s/40lbqd2bfxwm1qv8k6dy8qwyq48qd6xg).
- Once the content is reviewed (with stakeholders or SME of the topic) and finalized. 
- Copy the content from the Sketch file into the .mdx file for the markdown publishing process to start.
- Once complete, create the Pull Request and review, using the Preview link, to be sure it matches the Sketch file design
- When ready to deploy, include Jenny as a PR Reviewer and Approver.
- Jenny will review and merge the PR

#### Acceptance criteria
- [x] Content crafting is done.
- [x] Asset image creation is done (if needed)
- [x] Page design is done (if needed)
- [x] Publishing with markdowns is done.
- [x] QA'd by Jenny
- [x] Web page preview is approved by Linda, Jeff, and Wonil
- [x] Web page is published

**Comment by JennySanchez** [comment]
**BOX doc for making content edits:**
https://ibm.box.com/s/xfep7c44ui0ariakoi09lb9uu0ra1u19

**Comment by JennySanchez** [comment]
Initial content was reviewed with Linda and Jeff today. Round one content in markdowns and PR can be viewed [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/695).

**Comment by JennySanchez** [comment]
Hi @ljcarot This is the MVP version of the Pattern contribution page. Can you take a look and let me know if there's any edits needed before publishing? Thank you.

**Comment by ljcarot** [comment]
In box? or on gatsby? @JennySanchez

**Comment by ljcarot** [comment]
Found the latest link...it’s not for publishing.  The How to section is incomplete

**Comment by JennySanchez** [comment]
Hi @ljcarot We currently do not have templates for documentation, so I update the How to section copy to let the adopters know the templates are coming soon. Since the templates will take a while to get it done, I thought we can get the content out now and work on the template. Other than that, do you see any big differences between the Patterns contribution from Carbon and the one in the preview?

FYI: All documentation templates (in markdown) will be on the ideation board for planning and work in Sprint 20-23.

`The Patterns contribution from Carbon `

![Screenshot_2020-10-22 Patterns – Carbon Design System](https://user-images.githubusercontent.com/45213839/96884446-215e6500-1447-11eb-8cf5-85eab3e8c77a.png)


`The Patterns contribution in Preview.
`

![Screenshot_2020-10-22 Carbon for IBM com](https://user-images.githubusercontent.com/45213839/96884482-2a4f3680-1447-11eb-9544-cfdea29adcdf.png)

**Comment by JennySanchez** [comment]
Task completed and the PR detail can be viewed via PR [723](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/723#pullrequestreview-521942961).
