### ISSUE TITLE
Some pages scroll horizontally on mobile

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom-website#697]
## Detailed description

When scrolling vertically on a mobile device, some pages show horizontal scroll.

See the [videos](https://ibm.box.com/s/28rrum3rzdx61xv71itxg2zdgj3sxzwt) 

- Most pages under the "Components" section
- Some pages under guidelines
- Dev to research whether this root cause is the component or the Gatsby theme

## Steps to reproduce the issue

1. Open the Carbon for IBM.com website on a mobile device
2. Open the "Components / Lead space" page  (This behavior does not happen on the Home Page and the Card component page)
3. Start scrolling down
4. While scrolling vertically, also try to scroll horizontally.

**Comment by JennySanchez** [comment]
**Note:** 👉The page that shows the horizontal scroll is on the **Components overview page**.
