### ISSUE TITLE
Leadspace Alignment Style Model

### ISSUE THREAD

**Issue by mfearer94** [carbon-design-system/carbon-for-ibm-dotcom-website#710]
**Is your feature request related to a problem? Please describe.**
An issue we currently have is there is no designation of what the alignment of copy should be in the leadspace.

**Describe the solution you'd like**
The alignment of copy should first be dependent on if "search" is enabled within the leadspace. If it is, then the leadspace is center aligned.
If the page components are full-width, then align the leadspace content to page structure

**Describe alternatives you've considered**
We had a discussion about different page templates, the use of photography, and page structure, but we did run into some conflicting logic so the above option is the most high-level model that allows for flexibility, but also structure.

**Additional context** Add any other context or screenshots about the feature
request here.

**Comment by wonilsuhibm** [comment]
@mfearer94 Thanks for submitting the issue. It seems that you folks found problems with the logic that we agreed upon. I'd like to learn more about it. Can you either describe it here or schedule a meeting to go over your findings, please?

The previous logic was:
1. Lead space content aligns with the page's primary content.
2. When there is a background image in the lead space, the lead space should be left-aligned.

See the image below:
<img width="1523" alt="Screen Shot 2020-11-12 at 8 54 05 AM" src="https://user-images.githubusercontent.com/30183447/98948613-a8da4980-24c4-11eb-9dc6-431d8a2bf0a3.png">


Thank you!

**Comment by wonilsuhibm** [comment]
Here is an updated visual with more example:
![Screen Shot 2020-11-12 at 10 18 29 AM](https://user-images.githubusercontent.com/30183447/98960325-4daf5380-24d2-11eb-9c42-d04a05a347af.png)

The source Sketch file is here: https://ibm.box.com/s/7d54swktwrudnb5svodbrinrttsnsiky

**Comment by wonilsuhibm** [comment]
Per today's meeting, here are the agreed-upon guidelines around the lead space content alignment:

1. The lead space content should align with the primary content on the page.
2. When there is a background image, the lead space content should align to the left regardless of the page content.
3. When there is a search bar in the lead space, it should be center-aligned.

@mfearer94 @oliviaflory @ltitle @shixiedesign Please confirm. Once it's confirmed, we will move on to publishing this on our website.

**Comment by mfearer94** [comment]
This is perfect! Thank you @wonilsuhibm
