### ISSUE TITLE
Create production guideline

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#722]
> As a Carbon for IBM.com adopter, 
> I need guidance to help me make sure my contribution can be prepared as complete as possible for production, 
> so that the Carbon for IBM.com team can add my contribution to the system as efficiently as possible.

#### Resources & Notes

The Carbon Production Guideline for reference can be viewed [here](https://github.com/carbon-design-system/carbon-website/wiki/Production-guidelines). The link is lives under the Contribution/[Documentations](https://www.carbondesignsystem.com/contributing/documentation)/Guidelines for writing content section.

We might want the guideline to live on the Wiki or Guideline section of the website.

#### Tasks

- Collaborate and work on the production guideline draft with @jeffchew 
- Review the guideline content with @ljcarot and @wonilsuhibm 
- Make edits based on the review outcome
- Finalize the guideline

#### Acceptance criteria

- [ ] Product guideline is ready to be linked from the website for adopters

**Comment by JennySanchez** [comment]
Production guideline draft can be viewed [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Production-guidelines).

@jacobottesen-dgc Can you take a look and let me know if you spot any edits needed?
@oliviaflory Can you take a look at the Spec guidelines section and see if there's anything different than what we discussed with Wonil?

Thank you.

**Comment by JennySanchez** [comment]
@wonilsuhibm Can you take a look at the [production guideline](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Carbon-for-IBM.com-Production-guidelines) (MVP version) and let me know what do you think? Especially the File Type section. Thank you.

**Comment by wonilsuhibm** [comment]
@JennySanchez Thank you. Looks great.

- I added tips and tricks content from the other page. Let me know what you think.
- On the wiki navigation, should `General best practices` be moved under `design guideline drafts`, and `Carbon for IBM.com Production guidelines` moved to `Pulishing guidelines`?

**Comment by JennySanchez** [comment]
@wonilsuhibm Agreed with the nav edits and updated.
