### ISSUE TITLE
Gastby Theme update - for new App Switcher

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#724]
> As a Carbon for IBM.com adopter 

> I need a way to see the unified resources ist in the app switcher

> so that I can find the resources across all websites in the IDL ecosystem.

#### Additional information
See [IDL website](https://www.ibm.com/design/language/) for live demo. 

(Current)
![Screen Shot 2020-10-28 at 3 49 38 PM](https://user-images.githubusercontent.com/45213839/97496503-056f2d80-1937-11eb-9d6c-ed049243da8e.png)

(Updated)
![Screen Shot 2020-10-28 at 3 49 47 PM](https://user-images.githubusercontent.com/45213839/97496514-0902b480-1937-11eb-8d70-30f777d06ac0.png)

#### Acceptance criteria
- [ ] Carbon for IBM.com website app switcher has the same set as the IDL website

**Comment by JennySanchez** [comment]
Hi @jeffchew . The App Switcher is updated and live on the [website](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/). Do you need anything else from me? If not, let's move this task issue to the Done column?

![Screen Shot 2020-11-03 at 11 10 16 AM](https://user-images.githubusercontent.com/45213839/98017659-2e734080-1dc5-11eb-8877-d6ba466f3c2d.png)

**Comment by jeffchew** [comment]
This task is complete.
