### ISSUE TITLE
Website content publishing: Carousel/Components section (Layout) - Target Dec 4, 2020

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#732]
@RobertaJHahn commented on [Fri Oct 30 2020](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4374)

#### User Story

> As an Carbon for IBM.com adopter, 

> I need a way to learn more about the `Carousel` component

> so that I can utilize the component to my day to day work.

#### Additional information

- Take a look at the [storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/overview-getting-started--page) - so you know how the component works.   You will also use Storybook as a reference to accurately include the images in the Sketch file.
- Download this [Sketch template](https://ibm.box.com/s/66v0t127kdgo3xqt3u5f7dl56skpealk) to your machine to make the updates. Please review the image set up and the best practices in the file as well.  Name the Sketch file with the following convention: Name of the pattern + version. ex: `Feature card block v1.0`
- Navigate to the visual spec file within this [Carbon for IBM.com Box folder](https://ibm.box.com/s/vo3u9mxn8y7a5d7zoqvrvz7aalbf2yu3) and find the spec file under Components folder - The image that works successfully for most patterns is the 1312px image.  Adjustments may be needed to have this image accurately reflect the Storybook designs.
- Once complete, save the revised Sketch file in the Components folder / sub-folder [here](https://ibm.box.com/s/pyu51d278bp1nv1kvgpo8zsp53wvx5x3).
- Export the individual images with a 2X setting, saving them into the Layout Pattern sub-folder that contains the Sketch file.  These exported images will be used when creating the Markdown for publishing
 - Use this Sketch file to create the Markdown version of the web page in [Github](https://github.com/carbon-design-system/ibm-dotcom-library-website/tree/master/src/pages/patterns).
    - Find the .mdx file for the Layout Pattern assigned
    - Copy the content from the Sketch file into the .mdx file
    - Once complete, create the Pull Request and review, using the Preview link, to be sure it matches the Sketch file design
    - When ready to deploy, include Jenny, Linda, Jeff and Wonil as a PR Reviewers and Approvers.
    - Jenny will review and merge the PR

#### Acceptance criteria
- [x] Content crafting is done.
- [x] Asset image creation is done.
- [x] Page design is done.
- [x] Publishing with markdowns is done.
- [x] QA'd by Jenny
- [x] Web page preview is approved by Linda, Jeff and Wonil
- [ ] Web page is published

**Comment by jacobottesen-dgc** [comment]
Nov 11th started putting together guidelines for carousel component: https://ibm.ent.box.com/notes/740389822384

**Comment by JennySanchez** [comment]
Hi, @jacobottesen-dgc  Is the draft ready for review or it's WIP?

**Comment by jacobottesen-dgc** [comment]
@JennySanchez It's still WIP. I need to work on the images and refine the content down

**Comment by JennySanchez** [comment]
Got it. No prblem @jacobottesen-dgc, let me know if you need anything.

**Comment by jacobottesen-dgc** [comment]
All content is updated in this PR: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/747

I am having trouble with pulling in the Development documentation table from the json file.

**Comment by JennySanchez** [comment]
@RobertaJHahn This task is not completed and we need to update the milestone to Sprint 20-24 (current sprint).

**Next step:** 

- I will fix the development documentation table and review the content.
- @wonilsuhibm @oliviaflory Can you take a look at the content via [PR 747](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/747) from Jacob and provide feedback? Thank you.

**Comment by JennySanchez** [comment]
**Note:** There's a discussion around the naming of the Carousel component. Based on the group discussion on Slack, we will rename the component from "Carousel"  to "Card section – carousel". 

The latest updates can be viewed in the [PR](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/747).

**Comment by JennySanchez** [comment]
Page merged and task completed.
