### ISSUE TITLE
Content crafting and publishing: Contribution/Documentation page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#745]
#### User Story

> As an IBM.com Library adopter, 

> I need guidance on how to contribute Documentations to the IBM.com Library website,

> so that I can support the growth of the IBM.com Library. 

#### Additional information

- Work on the content by following the [publishing process](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj) as much as possible and as needed.
- Craft content based on the idealization outcome of the I[deation: Contribution Detail page](https://github.com/carbon-design-system/digital-design-ideation/issues/141) task on the ideation board.
- Create the website design with the Sketch App as needed and the Sketch publishing template can be found on the [BOX folder](https://ibm.box.com/s/ma72t84m75fvd3qqkyz8cm6gfx9b7vou). Once complete, save the revised Sketch file in the Guideline folder / sub-folder [here](https://ibm.box.com/s/40lbqd2bfxwm1qv8k6dy8qwyq48qd6xg).
- Once the content is reviewed (with stakeholders or SME of the topic) and finalized. 
- Copy the content from the Sketch file into the .mdx file for the markdown publishing process to start.
- Once complete, create the Pull Request and review, using the Preview link, to be sure it matches the Sketch file design
- When ready to deploy, include Jenny as a PR Reviewer and Approver.
- Jenny will review and merge the PR

#### Acceptance criteria

- [x] Content crafting is done.
- [x] Asset image creation is done (if needed)
- [x] Page design is done (if needed)
- [x] Publishing with markdowns is done.
- [ ] QA'd by Jenny
- [ ] Web page preview is approved by Linda, Jeff, and Wonil
- [ ] Web page is published

**Comment by JennySanchez** [comment]
@ljcarot Can you take a look at the Documentation page under the Contribution section and let me know if any edits needed? The preview can be found in [PR 744](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/744. )This page is very simple and will be linked to the production guideline I am working on via task issue [#722](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom-website/722).

**Comment by ljcarot** [comment]
Done and approved

**Comment by JennySanchez** [comment]
Thanks, Linda.
