### ISSUE TITLE
Website content crafting and publishing: (Components/ Link List section

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom-website#802]
## Objective
Provide Carbon for IBM.com adopter the best practices and guidance they need to adopt Carbon for IBM.com.  

**This content may be created as a Link List variation on the website.  Reach out to Jenny Sanchez and Wonil Suh to help make the decision.**

## General publishing process
Please make sure you always start the content crafting process by viewing the **[2020 website content publishing process box document](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj)** first.

## Publishing for Components section website page
- Content crafting starts as soon as the design is finalized. 
- Components section includes UI components and Layout components.
- The content can be at the MVP level. MVP means the content meets the basic needs of an adopter for learning. It does not mean the content crafting will or should stop at this stage. Future enhancement should be working on with a separate task issue.
- MVP content publishing template and requirement can be found in the Publishing template and best practices/[_UI and Layout Components folder](https://ibm.box.com/s/8p9k496ohera4aa9zge9syxyehz5p7h0).
- Please use the visual and design spec files inside of the [Carbon for IBM.com Box folder](https://ibm.box.com/s/vo3u9mxn8y7a5d7zoqvrvz7aalbf2yu3) as a reference. 
- Content publishing to the live website can be code or markdowns. If you need guidance on how to start with markdowns, please see the step by step instruction in the [Editing and publishing in Github Box document](https://ibm.box.com/s/as8fo8gcecvizngxgq2dpuk4po2alq7t).
- When the page is published, please also make sure the components table list on the [Overview page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/overview) is updated as part of the publishing task.

## File naming and storage
- Name the Sketch file with the following convention: Name of the category + components/pattern/guideline + version. ex: Components-Feature card block v1.0, Guidelines-Expressive theme v1.0, Help-Overview v1.0 and etc.
- Please save all content publishing work files (box, markdowns link, or Sketch file) in the proper sub-folder under the[ ✍️ Content + Design folder](https://ibm.box.com/s/tty3jhshkt6l18jkn2v5ac2uznyjexns).

## Publishing acceptance criteria
- [x] Content crafting is done.
- [x] Asset image creation is done.
- [x] Page design is done (as needed).
- [x] Publishing with markdown is done.
- [x] Update the [Overview page component table list](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/overview/) with the new component name, link to the newly published component page, description and status when the markdown is done.
- [x] Create a thumbnail of the new component.   **Thumbnail examples can be viewed [here](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/gallery/).  The Sketch file that will help you get started can be found [here](https://ibm.ent.box.com/file/749605054637?s=hyzeqfb7zqov1j3es4p6kplr6r15flat).  If you are not familiar with component thumbnail creation, please ask another designer or Jenny for assistance.  Once the thumbnail is created, please review with Wonil for approval, then export the file as an SVG for implementation.**
- [x] Add the new component thumbnail to the [Overview page/Gallery view](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/gallery) by adding the image file to the `components.json` markdown file. Please follow the file naming format so it can be linked to the website page automatically (ex: thumbnail svg file for "Card section – Carousel" should be "cardsection-carousel.svg").
- [x] QA'd by Jenny.
- [x] Web page preview is approved by Linda, Jeff, and Wonil.
- [x] PR merged by Jenny.
- [x] Web page is published and live on the website.

**Comment by JennySanchez** [comment]
**Final design from Jina:**

[https://app.zenhub.com/files/202376156/0e59549d-95a4-47fb-b546-f2f4e9c642b9/download](https://app.zenhub.com/files/202376156/0e59549d-95a4-47fb-b546-f2f4e9c642b9/download)

**Comment by JennySanchez** [comment]
**Note:** Talked to Jina today, and she is going to start the markdown process soon.

FYI - @RobertaJHahn

**Comment by jyoon25** [comment]
Thumbnail img link: https://ibm.box.com/s/f1mzgb4dcw7lyvd85ggv21zn7jq000e4

@JennySanchez I don't have permit to upload imgs to github. Can you help me to upload the imgs in github? 
Github link: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/tree/master/src/images/component
All imgs folder link: https://ibm.box.com/s/jxmxb6d8rfbvbf9hnz9rt5mh9k9wxytn



---
title: Link list section
description: Component guideline page for Link list section.
---

import { ComponentStatus } from ‘components/ComponentList’;
import ComponentDescription from ‘components/ComponentDescription’;
import ComponentFeedback from ‘components/ComponentFeedback’;

<ComponentDescription name=“Link list section” type=“ui” />

<AnchorLinks>

<AnchorLink>Default</AnchorLink>
<AnchorLink>Variations</AnchorLink>
<AnchorLink>Design and functional specifications</AnchorLink>
<AnchorLink>Development documentation</AnchorLink>
<AnchorLink>Feedback</AnchorLink>

</AnchorLinks>

## Default
The Link list section displays links in a list format with a semibold heading on the left side.
<Row>
<Column colMd={8} colLg={8}>

![Image of Card component](../../images/component/link-list-section/link-list-section-default.jpg)

</Column>
</Row>


## Variations

### One to three links
This variation divides the content’s remaining 8 column layout into 1 column when there are 1 to 3 links.

<Row>
<Column colMd={8} colLg={8}>

![Image of Card component](../../images/component/link-list-section/link-list-section-one-to-three-links.jpg)

</Column>
</Row>

### Four to six links
This variation divides the content’s remaining 8 column layout into 2 columns when there are 4 to 6 links.

<Row>
<Column colMd={8} colLg={8}>

![Image of Card component](../../images/component/link-list-section/link-list-section-four-to-six-links.jpg)

</Column>
</Row>

### Seven or more links
This variation divides the content’s remaining 12 column layout into 3 columns when there are 7 or more links.

<Row>
<Column colMd={8} colLg={8}>

![Image of Card component](../../images/component/link-list-section/link-list-section-seven-or-more-links.jpg)

</Column>
</Row>

## Design and functional specifications
The design specs and functional specs for (Name of the Component or Pattern) can be viewed <a href=“https://ibm.box.com/s/mktywz4ujxo9yiiu371kgzbib93uc2po” target=“_blank”>here</a>.


## Development documentation

<ComponentStatus name=“Link-list-section” type=“ui” />


## Feedback

<ComponentFeedback />

**Comment by jyoon25** [comment]
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/855

**Comment by JennySanchez** [comment]
Website page is published and live on the [website](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/link-list-section).
