### ISSUE TITLE
[Website] Contrbution: Craft and Published step by step for generating a pull request

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#807]
> As a Carbon for IBM.com contributor, 

> I need a way to learn how to generate and submit PR, 

> so that I can contribute back to the Carbon for IBM.com without trouble.

#### Note

- We need to create step by step guidelines to support adopters, so they know how to generate and submit a PR for contributions.

- The "Editing Creating a PR through github.com UI" can be viewed [here](https://github.com/carbon-design-system/carbon-website/wiki/Editing-Creating-a-PR-through-github.com-UI).

![Screen Shot 2021-01-06 at 4 35 38 PM](https://user-images.githubusercontent.com/45213839/103826830-3eb1d100-503d-11eb-95ca-c35a15ffa792.png)

- The "Editing pages" section does currently not exist on our website yet. Once the step by step content is ready, we will add it to the [Documentation page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributions/documentation).

![Screen Shot 2021-01-04 at 2 03 48 PM](https://user-images.githubusercontent.com/45213839/103574505-b513cf00-4e95-11eb-9fe5-a783101d65a7.png)

#### Steps
- [ ] How to generate and submit a pull request content crafting is done.
- [ ] Asset image creation is done
- [ ] Publishing with markdowns is done (website repo wiki).
- [ ] QA'd by Jenny
- [ ] "Editing page section" content is added to the live website
- [ ] Web page preview is approved by Linda, Jeff, and Wonil
- [ ] Web page is published

#### Acceptance criteria

- [ ] "Creating a PR through github.com UI" page and content is added to the [website repo wiki.](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki)
- [ ] The "Editing page section" content is added to the Documentation page and live on the website.

**Comment by JennySanchez** [comment]
@jeffchew This task is created based on our Slack channel. This documentation is the "good to have" for adopter support. It will be great if a developer can create the step by step document (or collaborate on this with a designer - if needed) on our team.

**Comment by JennySanchez** [comment]
**Note: Addtional resources shared by James**

Talking about how to submit an issue...

You can link them directly to create a page here under components.
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/new/master/src/pages/components

But even after that creating a component on the website involves more than just a single page right?

1. They first have to create the component.mdx file
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/new/master/src/pages/components

2. Then they have to edit it into the navigation yaml file.
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/nav-items.yaml

3. They also have to update the components data object.
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json

4. Then it also needs to be added to the overview page.
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/pages/components/overview.mdx

Each time requires a brief commit message, and to submit the change as a PR.

**Comment by RobertaJHahn** [comment]
Included in May 3 engineering meeting agenda.

**Comment by janchild** [comment]
@janchild to assess
