### ISSUE TITLE
[Website] Contribution: Craft and Published step by step for install tools and fork the repo

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#808]
> As a Carbon for IBM.com contributor, 

> I need a way to learn how to install tools and fork the repo, 

> so that I can contribute back to the Carbon for IBM.com without trouble.

#### Note

- We need to create step by step guidelines to support adopters, so they know how to install tools and fork the repo.

- The "install tools and fork the repo//Editing Updating content on carbondesignsystem.com" from Carbon can be viewed [here](https://github.com/carbon-design-system/carbon-website/wiki/Editing-Updating-content-on-carbondesignsystem.com).

![Screen Shot 2021-01-06 at 4.45.45 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/3373e7ab-a290-41da-ac77-8108690f6e02)

- The "Making regular content update" section does currently not exist on our website yet. Once the step by step content is ready, we will add it to the [Documentation page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributions/documentation).

![Screen Shot 2021-01-04 at 1 56 52 PM](https://user-images.githubusercontent.com/45213839/103574156-112a2380-4e95-11eb-8dcb-fa7e15081594.png)

#### Steps
- [ ] How to install tools and fork the repo content crafting is done.
- [ ] Asset image creation is done
- [ ] Publishing with markdowns is done (website repo wiki).
- [ ] QA'd by Jenny
- [ ] "Making regular content update" content is added to the live website
- [ ] Web page preview is approved by Linda, Jeff, and Wonil
- [ ] Web page is published

#### Acceptance criteria

- [ ] "How to install tools and fork the repo" page and content is added to the [website repo wiki.](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki)
- [ ] The "Making regular content update" section content is added to the Documentation page and live on the website.

**Comment by JennySanchez** [comment]
@jeffchew This task is created based on our Slack channel. This documentation is the "good to have" for adopter support. It will be great if a developer can create the step by step document (or collaborate on this with a designer - if needed) on our team.

**Comment by RobertaJHahn** [comment]
Included in the May 3 engineering meeting agenda.

**Comment by janchild** [comment]
@janchild to assess

**Comment by shixiedesign** [comment]
This seems like development documentation that shouldn't live on the website, but in github repo. Closing for now and feel free to reopen if anyone have more background.
