### ISSUE TITLE
Dev - update the Components/Gallery view images

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#845]
Based on the audit work [#795](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/795), we are ready to make changes via code.

**Overall audit outcomes:**
![TableList.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/35ce86a9-b8ee-45f2-874d-609f267f8c32)
![Gallery.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/d53ebce0-c2bf-46ba-b7f6-30c76d774907)

**All the updated SVGs can be found in this [BOX folder](https://ibm.box.com/s/xq7aqa339zywrzvrg6l6nk9n3e2fpv8e) (Updated thumbnails (02-08-2021)**

**Acceptance criteria**
- [ ] Items from the audit are updated and live on the website.

**Comment by annawen1** [comment]
@JennySanchez just to note in the first screenshot - it looks like you corrected `Locale modal` to `Local modal` - I believe the `Locale` spelling is intended

**Comment by annawen1** [comment]
@JennySanchez just to note in the first screenshot - it looks like you corrected `Locale modal` to `Local modal` - I believe the `Locale` spelling is intended
