### ISSUE TITLE
Website [Masthead] website page updates

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#853]
@wonilsuhibm @oliviaflory @photodow @shixiedesign 

Based on the Sprint planning conversation today, there are a few updates we need to make to the Masthead or Mega Menu on the website. Please add the items you noticed below for the update task to be estimated.

👉 **Please indicate if they are, Update with the current content, New section needs to be added, New website page needs to be created for it, or others (add more detail, please)**.

**Comment by shixiedesign** [comment]
From what I remember: 
- [ ] add example of Text wrap in mobile 
- [ ] include latest spacing updates since Lila's pass on Cloud mega menu 

Q: Is there need to include the Products & solutions tab open at all? If not there's no other action items I know..

**Comment by JennySanchez** [comment]
During a conversation with @lily-kenney , Lila, and @oliviaflory this morning, Lila mentioned we have a few changes made to the Masthead (such as the label type token, login icons, etc.). The recommendation is to update the design spec file first before we update the content on the website, so we might need to move this work to a different sprint.

@shixiedesign @DragosRistici FYI.

**Comment by lily-kenney** [comment]
I don't think mega menu needs to be called out as a separate section as we discussed leaving the content as is and adding a link to the IA office hours for anyone who has questions about adopting the L0 or L1 menu. IA office hours are weekly. They can sign up to join the IA office hours at: https://ec.yourlearning.ibm.com/w3/join/meeting/10144838.
