### ISSUE TITLE
[Components section] Content coming soon message implementation

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#886]
### Problem to solve

Currently, we have "Design and functional specifications, Development documentation, and Feedback" sections as the base content for the website page. The development team populated the page when a new component developed.

However, when adopters visit the website, they see a simple page without guidelines they are looking for and have no idea when DDS Team will provide the guideline or additional information about the component. We need to create a treatment to inform the adopter the rest of the guidance is in work progress to set the right expectation.

### Steps:

1. Review the blue "Additional usage guidelines are coming soon" notification design with Jenny
![Screen Shot 2021-03-03 at 1 23 19 PM](https://user-images.githubusercontent.com/45213839/109860515-e1449580-7c23-11eb-9d83-f6c2f8a61ab0.png)
2. Add the blue "Additional usage guidelines are coming soon" notification on the existing website page (see list below) updated and add it to the development master file implementation via Code as well.

- Button group
- Card group
- Carousel
- Content item — horizontal
- Dotcom shell
- Image
- Layout
- Pictogram item
- Quote

3. Review PR with Jenny

### Note:

👉 The blue inline notification treatment is a core Carbon component, and the detail can be viewed [here](https://www.carbondesignsystem.com/patterns/notification-pattern).

### Acceptance criteria
- [x] Notification treatments are updated on all existing website pages
- [x] Notification treatment is added to the development master file

**Comment by RobertaJHahn** [comment]
Added the topic and Jenny to the March 8 engineering meeting agenda.

**Comment by shixiedesign** [comment]
I did this work and hopefully correctly. Will be reviewing PR with Jenny. @RobertaJHahn I don't think we need to go over this the dev team. Thanks! 
PR: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/898

**Comment by JennySanchez** [comment]
@shixiedesign Thank you for working on it. I was going to do that later today before I log off.

I did not see the notification popping up on the Button Group page. You?
Also, I see the Notification treatment is added to the development master file is checked off. Where did you add that?

**Comment by RobertaJHahn** [comment]
@shixiedesign This topic is included in the Monday, March 15, meeting agenda.

**Comment by shixiedesign** [comment]
Went over this during Monday's engineering call. Kenny confirmed there's no "template" and sections of the page are just copied from other existing pages. Therefore I checked off "Notification treatment is added to the development master file".

**Comment by RobertaJHahn** [comment]
Closing based on comments above.
