### ISSUE TITLE
12 [Content group - banner] publish the new website page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#891]
@RobertaJHahn commented on [Thu Mar 04 2021](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5371)

 ## Objective
Provide Carbon for IBM.com adopter the best practices and guidance they need to adopt Carbon for IBM.com.

## General publishing process
Please make sure you always start the content crafting process by viewing the **[2020 website content publishing process box document](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj)** first.

## Publishing for Components section website page
- Content crafting starts as soon as the design is finalized. 
- Components section includes UI components and Layout components.
- The content can be at the MVP level. MVP means the content meets the basic needs of an adopter for learning. It does not mean the content crafting will or should stop at this stage. Future enhancement should be working on with a separate task issue.
- MVP content publishing template and requirement can be found in the Publishing template and best practices/[_UI and Layout Components folder](https://ibm.box.com/s/8p9k496ohera4aa9zge9syxyehz5p7h0).
- Please use the visual and design spec files inside of the [Carbon for IBM.com Box folder](https://ibm.box.com/s/vo3u9mxn8y7a5d7zoqvrvz7aalbf2yu3) as a reference. 
- Content publishing to the live website can be code or markdowns. If you need guidance on how to start with markdowns, please see the step by step instruction in the [Editing and publishing in Github Box document](https://ibm.box.com/s/as8fo8gcecvizngxgq2dpuk4po2alq7t).
- When the page is published, please also make sure the components table list on the [Overview page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/overview) is updated as part of the publishing task.

## File naming and storage
- Name the Sketch file with the following convention: Name of the category + components/pattern/guideline + version. ex: Components-Feature card block v1.0, Guidelines-Expressive theme v1.0, Help-Overview v1.0 and etc.
- Please save all content publishing work files (box, markdowns link, or Sketch file) in the proper sub-folder under the[ ✍️ Content + Design folder](https://ibm.box.com/s/tty3jhshkt6l18jkn2v5ac2uznyjexns).

## Publishing acceptance criteria
- [x] Content crafting is done.
- [x] Asset image creation is done.
- [x] Page design is done (as needed).
- [x] Publishing with markdown is done.
- [ ] Update the [Overview page component table list](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/overview/) with the new component name, link to the newly published component page, description and status when the markdown is done.
- [ ] Create a thumbnail of the new component.   **Thumbnail examples can be viewed [here](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/gallery/).  The Sketch file that will help you get started can be found [here](https://ibm.ent.box.com/file/749605054637?s=hyzeqfb7zqov1j3es4p6kplr6r15flat).  If you are not familiar with component thumbnail creation, please ask another designer or Jenny for assistance.  Once the thumbnail is created, please review with Wonil for approval, then export the file as an SVG for implementation.**
- [ ] Add the new component thumbnail to the [Overview page/Gallery view](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/gallery) by adding the image file to the `components.json` markdown file. Please follow the file naming format so it can be linked to the website page automatically (ex: thumbnail svg file for "Card section – Carousel" should be "cardsection-carousel.svg").
- [ ] PR QAed and merged by Jenny.

### Acceptance criteria
- [ ] Web page is published and live on the website.

**Comment by JennySanchez** [comment]
@shixiedesign Is this a brand new website page we need to create or add new content to an existing page? If it's to a current page, we do not have a "Content group – simple" but not a "Content group" page.

I asked because I can not find the "Content group – banner" in our Storybooks, not the banner option under Content group – simple variants.

(Web components)
![Screen Shot 2021-04-05 at 12 19 00 PM](https://user-images.githubusercontent.com/45213839/113603145-2ab04800-9609-11eb-9e27-611ac60faa60.png)

(React)
![Screen Shot 2021-04-05 at 12 19 08 PM](https://user-images.githubusercontent.com/45213839/113603148-2be17500-9609-11eb-81d5-f52c818f1ed9.png)

**Comment by JennySanchez** [comment]
**Note:** Based on the discussion from yesterday, this component is still inbuilt.

**Comment by shixiedesign** [comment]
### Summary

This component is designed as a subtle callout. This component is intended for content that are not directly sending users down the journey towards buy, but instead, content here could be a tangentent or announcement type of thing, supplementary to the page's main focus. 

### Discussions that can be turned into guidance 
 
There are some very long threads of discussion on this component. Some selected discussions from Slack that could be turned into guidance: 

From Kirby https://cognitive-app.slack.com/archives/G01NL7EMMGU/p1615318623003200?thread_ts=1615258107.003600&cid=G01NL7EMMGU
> An additional CTA or callout added to the bottom of another component. This will be a brand new component that will use low contrast. This component is what we want to contribute to the DDS library for April. 

From Shixie https://cognitive-app.slack.com/archives/G01NL7EMMGU/p1615399259003500?thread_ts=1615258107.003600&cid=G01NL7EMMGU
>I think he meant it sits below other components.
>> That was to serve as an additional CTA or callout that was attached to the bottom of another component.
> But yeah @shawn.hoglund @kirbyevans if you have any live pages using this component to point us to that would be great. I can see it > living under the more text-heavy sections.

From Shixie https://cognitive-app.slack.com/archives/G01NL7EMMGU/p1615919455000600?thread_ts=1615258107.003600&cid=G01NL7EMMGU
> I'm comfortable with this being its own component because it is a CTA attached to headline. I'd add **tangential content / announcement** to part of the intent,

**Comment by JennySanchez** [comment]
@RobertaJHahn We need to move this task to Sprint 21-08.

**Comment by JennySanchez** [comment]
@shixiedesign The content we need to craft is based on the MVP content structure (see live example [here](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/content-block-media) or markdown template [here](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/components)). While all the discussions are great for gaining insight, it does not help with content crafting. 

Ideally, we should follow the publishing priority list we worked on and agreed on in [Mural](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1615215157517?sender=chsanche&key=38c4cb66-c300-4626-b733-8b2bcee40e29). By doing so, I know what components or guidelines is publishing task I can work on besides of other website-related priority I have. Or assign a designer to work on it. Ideally, we should work on at least two Components of content publishing tasks for the website.


**If Content group – banner component website content is indeed the highest priority and needs to be worked on as soon as possible, we can do one of the three things listed below to get the task done:**

1.I can reset the priority I have for Sprint 21-08 and work on this task. I will need to know who I should be working with (Kirby? Shawn?) to set up the design interview to ask questions based on what we need from the content structure and craft content. 
2. You can craft the content based on the structure requirement I share above, and we can review it together.
3. We can assign this task to one of the designers to craft the content based on the structure requirement I share above, and we can review it together.

**Comment by JennySanchez** [comment]
Page content preview can be found in the [PR](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/940) [preview link]https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/940/index.html).

**Comment by JennySanchez** [comment]
@shixiedesign We need a thumbnail image for the [Gallery view](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/gallery) on the Components Overview page.
