### ISSUE TITLE
Website: create and publish training materials under Contribution

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#913]
## Objective:

As a Carbon for IBM.com adopter, I need training or tutorials to learn the knowledge I need to adopt Carbon for IBM.com.

---

## Note:

This Epic is identified as a High priority by Linda. We need to add the material to the website and possibility adding Tutorials pages to its prospect sections like what's on the Carbon website. 

---

## Steps:

- [ ] Planning - decided what we need to create to support adopters
- [ ] Create materials
- [ ] Add to the website

**Comment by RobertaJHahn** [comment]
All linked issues are closed.  Closing
