### ISSUE TITLE
Create Our Team page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#914]
We need a way to help adopters know who we are as a team, so that they know who to reach out to whenever they have questions.

Example: https://www.carbondesignsystem.com/all-about-carbon/the-team/

![Screenshot_2021-03-25 The Carbon team – Carbon Design System.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/c5dd4681-fef2-435b-9a2e-acbc51192cbb)

**Comment by shixiedesign** [comment]
Low priority
