### ISSUE TITLE
Ideate on the Birthday Cake version content structure for components website pages

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#915]
## Objective:
As the Carbon for IBM website grows, we need to add new sections and features to support adopter needs. 
It's time to build the Birthday Cake content! 

# 🎂

## The items for consideration are: (more to come)

- [ ] Component anatomy (from design spec)
- [ ] Use case examples/Case study
- [ ] Components preview modules (not sure)
- [ ] When to use and when not to use
- [ ] Accessibility best practice call out.

**Comment by JennySanchez** [comment]
- [ ] Content (for the copy used in the component, best practices, character counts, content width, etc.)

![Screen Shot 2021-04-16 at 12.23.13 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/ee2c581f-9152-4271-867d-3436e956991a)

**Comment by JennySanchez** [comment]
- [ ] Tabs on the page, especially for the Components section

**Comment by shixiedesign** [comment]
To be continued here #1077
