### ISSUE TITLE
Website [Get started and Designing] Content update based on the recent Expressive Theme changes

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#946]
## Objective

We need to update the content on a few website pages to reflect the Expressive Theme changes.

## Pages to be updated

- [x] Get started page
- [x] Designing page
- [x] Developing page
- [x] Resources page
- [x] FAQ page

### Acceptance criteria

- [x] Updated information on the pages listed above reflects the change in a PR.

**Comment by JennySanchez** [comment]
Work session scheduled for Thursday 05/20 11 to 11:45 am CT.

**Comment by shixiedesign** [comment]
I did a `cmd + F` search on the website and here are all the pages containing content on Expressive theme that should be addressed.
- /designing
- /developing
- /guidelines/overview
- /guidelines/expressive-theme
- /help/faqs
- /resources/overview

**Comment by shixiedesign** [comment]
## I also suggest we line this up in the form of a PR but not merge until after sprint 11

**Comment by JennySanchez** [comment]
**Note:**

Link to the IBM Tool page.
https://w3.ibm.com/design/toolbox/#/ui-design-tools/sketch/README

**Comment by JennySanchez** [comment]
- Most of the pages listed above are updated with the craft content. Since [the PR](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1002) won't be merged until July, we should take another look before merging.

- One thing we need to find out is the development package link. We need to find out from Jeff which package or packages need to be linked to.

- Olivia and I talked about revisiting the Designing page, and we might need new content and structure for that page. Still, for now, the necessary information about the Expressive theme is there. Task issue created so we can add notes, references, etc., in the meanwhile.
