### ISSUE TITLE
Can I continue using web design standard package(JS&CSS) file after our team was separated from IBM then join "Kyndryl"?"

### ISSUE THREAD

**Issue by bostonlf** [carbon-design-system/carbon-for-ibm-dotcom-website#959]
## Relevant information

we are using IBM standard file(JS&CSS) in our project(v8 - v18) , and our team will be separated from IBM then join "Kyndryl",may I know how to deal with the IBM starndard file URL in our project ?Can we continue using IBM standard file(JS&CSS) after our team was migrated to "Kyndryl"?"
file & URL as below
https://w3.ibm.com/ui/v8/css/v4-screen.css
www.ibm.com/common/v14/screen.css
www.ibm.com/common/v16/css/screen-uas.css
www.ibm.com/i/v14/rules/grey_rule.gif
www.ibm.com/i/v16/t/ibm-logo.gif
www.ibm.com/common/js/ibmcommon.js

## Name and organization
Boston
feilv@cn.ibm.com

**Comment by JennySanchez** [comment]
Hi @bostonlf, There are a few conversations on the #carbon-for-ibm-dot com slack channel regarding your question here after this issue was opened. Do you still have questions about using the web design standard package?

**Comment by ljcarot** [comment]
@bostonlf I would recommend not using anything that is going to be sunset.  I'll close this issue.  Please use Slack #carbon-for-ibm-dotcom for further communications.
