### ISSUE TITLE
Sticky behavior guidance 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#971]
We are starting to see a lot of sticky components - components that stays on page, pinned to an edge of the screen while users scroll through the page. These sticky components may be conflicting each other and we should provide guidance on **what gets to be sticky and when**. 

Current top sticky components:
- L0 
- L1
- Table of content - horizontal 
- Table of contents – vertical (medium & small breakpoints)
- Lead space search 

Current side sticky components: 
- Table of contents - vertical (desktop) 
- Back to top
- Site feedback 
- Let's talk (UMX)

Current sticky behaviors

| Situations  | What's sticky? |
| ----------------- | --- | 
| L0                          | L0 sticky |
| L0 + L1                  | L1 sticky |
| L0 + ToC horiz  | ToC horiz |
| L0 + L1 + ToC horiz  | ToC horiz |
| L0 + L1 + LS search  | LS search |
| L0 + ToC horiz + LS search  | LS search |
| L0 + L1 + ToC horiz + LS search  | LS search |

**Comment by jeffchew** [comment]
@shixiedesign wondering if it is a good idea to get a dev involved in this research? There's a lot of technical complexities to consider as we are discussing this in engineering huddle.

**Comment by shixiedesign** [comment]
Always great to have dev support on these - do you have a point person? @jeffchew

**Comment by jeffchew** [comment]
@RobertaJHahn can this be added as a refinement meeting agenda item to get a volunteer?

cc: @shixiedesign

**Comment by RobertaJHahn** [comment]
@shixiedesign Kenny is the consulting engineer whenever you decide to schedule the design work.

**Comment by shixiedesign** [comment]
There is a draft PR submitted by James that's a beginning of this work https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1368 

Re-opening this issue and closing the "continuation" issue because this one contains more meaningful info. Will reschedule it for 2022.
