### ISSUE TITLE
Website: add Component naming standards to the website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom-website#987]
### Objective:

Carbon for IBM.com adopters needs a way to understand how the component is named and how the naming structure works so that they can find the components they are looking for efficiently.

### Note:

See [New naming standards](https://ibm.box.com/s/xlq4romcyp50lnvwuaagyzzbmmesuxen) note and [#6091](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6091) for preparation. 

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3562653039633361363130323930306336643136643939312f32626538626665662d363531662d343832392d396](https://user-images.githubusercontent.com/45213839/118564943-e7ccae80-b736-11eb-863f-dbba28bbcccc.png)

### Steps:

- [ ] Ideate on the possible places on the website for the information to live.
- [ ] Refine the content if needed
- [ ] Publish the content on the website via markdowns
- [ ] Get feedback
- [ ] Finalize the content 

### Acceptance criteria

- [ ] Component naming standards is live on the website

**Comment by oliviaflory** [comment]
Will address this issue in #1285
