### ISSUE TITLE
[Website] Design how to present functional spec 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#999]
We currently have Website wiki documenting the Dependencies of Functional spec :tada: 

We would like to pull all information out of the word/pages documents. The rest of the info are: 
- Annotated image
- Content section
- [TBD]

**Comment by RobertaJHahn** [comment]
Will add to the June 1 Design planning meeting agenda

**Comment by shixiedesign** [comment]
Duplicated.
